PRECOMPILED_HEADER = precompile.h

HEADERS += \
    $$PWD/precompile.h \
    ../Src/DataManagement/CdmDataAccessHelper.h \
    ../Src/DataManagement/IdmDataAccess.h \
    ../Src/DataManagement/CdmValueBinaryDocument.h \
    ../Src/DataManagement/CdmValueBool.h \
    ../Src/DataManagement/CdmValueCharacterDocument.h \
    ../Src/DataManagement/CdmClass.h \
    ../Src/DataManagement/CdmClassGroup.h \
    ../Src/DataManagement/CdmClassManager.h \
    ../Src/DataManagement/CdmClassMethod.h \
    ../Src/DataManagement/CdmClassValidator.h \
    ../Src/DataManagement/CdmValueCounter.h \
    ../Src/DataManagement/CdmScheme.h \
    ../Src/DataManagement/CdmValueDate.h \
    ../Src/DataManagement/CdmValueDateTime.h \
    ../Src/DataManagement/CdmValueDictIntDouble.h \
    ../Src/DataManagement/CdmValueDictIntInt.h \
    ../Src/DataManagement/CdmValueDictIntString.h \
    ../Src/DataManagement/CdmValueDictStringDouble.h \
    ../Src/DataManagement/CdmValueDictStringInt.h \
    ../Src/DataManagement/CdmValueDictStringString.h \
    ../Src/DataManagement/CdmValueDouble.h \
    ../Src/DataManagement/CdmValueListDouble.h \
    ../Src/DataManagement/CdmExecutor.h \
    ../Src/DataManagement/CdmExecutorPreProcessor.h \
    ../Src/DataManagement/CdmExecutorAddOnManager.h \
    ../Src/DataManagement/CdmExecutorFormula.h \
    ../Src/DataManagement/CdmExecutorFunction.h \
    ../Src/DataManagement/CdmExecutorValidator.h \
    ../Src/DataManagement/CdmValueFloat.h \
    ../Src/DataManagement/CdmValueInt.h \
    ../Src/DataManagement/CdmValueListInt.h \
    ../Src/DataManagement/CdmJournalItem.h \
    ../Src/DataManagement/CdmLocatedElement.h \
    ../Src/DataManagement/CdmValueLong.h \
    ../Src/DataManagement/CdmSessionManager.h \
    ../Src/DataManagement/CdmMember.h \
    ../Src/DataManagement/CdmMessageManager.h \
    ../Src/DataManagement/CdmModelElement.h \
    ../Src/DataManagement/CdmModelElementBase.h \
    ../Src/DataManagement/CdmObject.h \
    ../Src/DataManagement/CdmObjectAdaptor.h \
    ../Src/DataManagement/CdmObjectContainer.h \
    ../Src/DataManagement/CdmContainerManager.h \
    ../Src/DataManagement/CdmValueContainerRef.h \
    ../Src/DataManagement/CdmContainerServices.h \
    ../Src/DataManagement/CdmValueObjectRef.h \
    ../Src/DataManagement/CdmProxyBase.h \
    ../Src/DataManagement/CdmQuery.h \
    ../Src/DataManagement/CdmQueryBuilder.h \
    ../Src/DataManagement/CdmQueryElement.h \
    ../Src/DataManagement/CdmQueryEnhanced.h \
    ../Src/DataManagement/CdmQueryResultElement.h \
    ../Src/DataManagement/CdmQueryResultObject.h \
    ../Src/DataManagement/CdmRights.h \
    ../Src/DataManagement/CdmSettings.h \
    ../Src/DataManagement/CdmValueString.h \
    ../Src/DataManagement/CdmValueListString.h \
    ../Src/DataManagement/CdmSystemVariables.h \
    ../Src/DataManagement/CdmValueTime.h \
    ../Src/DataManagement/CdmValue.h \
    ../Src/DataManagement/CdmValueEnum.h \
    ../Src/DataManagement/CdmValueFormula.h \
    ../Src/DataManagement/CdmValueListObjects.h \
    ../Src/DataManagement/CdmValueUser.h \
    ../Src/DataManagement/CdmValueUserGroup.h \
    ../Src/UserManagement/CumAccessor.h \
    ../Src/UserManagement/CumAccessorRight.h \
    ../Src/UserManagement/CumUser.h \
    ../Src/UserManagement/CumUserGroup.h \
    ../Src/UserManagement/CumUserManager.h \
    ../Src/DataManagement/datamanager.h \
    ../Src/DataManagement/IdmMessageManager.h \
    ../Src/DataManagement/IwmsDataAccessPlugin.h \
    ../Src/DataManagement/IwmsPluginInterface.h \
    ../Src/DataManagement/IwmsViewProxy.h \
    ../Src/DataManagement/CdmClassDiamondValidator.h \
    ../Src/SimpleApi/CsaValue.h \
    ../Src/SimpleApi/CsaModelElement.h \
    ../Src/SimpleApi/CsaClass.h \
    ../Src/SimpleApi/CsaClassManager.h \
    ../Src/SimpleApi/CsaContainerManager.h \
    ../Src/SimpleApi/CsaScheme.h \
    ../Src/SimpleApi/CsaFactory.h \
    ../Src/SimpleApi/CsaManager.h \
    ../Src/SimpleApi/CsaMember.h \
    ../Src/SimpleApi/CsaObject.h \
    ../Src/SimpleApi/CsaObjectContainer.h \
    ../Src/SimpleApi/CsaUser.h \
    ../Src/SimpleApi/CsaUserGroup.h \
    ../Src/SimpleApi/CsaLocatedElement.h \
    ../Src/SimpleApi/CsaQuery.h \
    ../Src/DataManagement/CdmExecutorBase.h \
    ../Src/DataManagement/CdmExecutorRuntime.h \
    ../Src/DataManagement/CdmExecutorRuntimeManager.h \
    ../Src/DataManagement/IdmExecutor.h \
    ../Src/DataManagement/CdmExecutorRemote.h \
    ../Src/DataManagement/CdmSession.h \
    ../Src/DataManagement/CdmDataAccessConfiguration.h \
    ../Src/DataManagement/IwmsPrinting.h \
    ../Src/DataManagement/IwmsPrintingPlugin.h \
    $$PWD/../Src/DataManagement/CdmPackage.h \
    $$PWD/../Src/DataManagement/CsaResultObject.h \
    $$PWD/../Src/DataManagement/IdmExecutorEngine.h \
    $$PWD/../Src/DataManagement/CdmExecutorEngineScript.h \
    $$PWD/../Src/DataManagement/CdmExecutorEngineJs.h \
    $$PWD/../Src/DataManagement/CdmGlobalContext.h \
    $$PWD/../Src/SimpleApi/CsaFunction.h \
    $$PWD/../Src/SimpleApi/CsaValueReference.h \
    $$PWD/../Src/DataManagement/CdmLogging.h \
    $$PWD/../Src/DataManagement/CdmLogEntry.h \
    $$PWD/../Src/DataManagement/CdmLogfileWriter.h \
    $$PWD/../Src/DataManagement/CdmLoggingAdaptor.h \
    $$PWD/../Src/DataManagement/CdmDataProvider.h \
    $$PWD/../Src/DataManagement/IwmsDataAccessManager.h \
    $$PWD/../Src/DataManagement/IdmEventStoreManager.h \
    $$PWD/../Src/DataManagement/IdmEventIterator.h \
    $$PWD/../Src/SimpleApi/IsaLocatedElement.h \
    $$PWD/../Src/SimpleApi/IsaModelElement.h \
    $$PWD/../Src/SimpleApi/IsaValue.h \
    $$PWD/../Src/SimpleApi/IsaClass.h \
    $$PWD/../Src/SimpleApi/IsaObject.h \
    $$PWD/../Src/SimpleApi/IsaMember.h \
	$$PWD/../Src/DataManagement/CdmConfigManager.h \
    $$PWD/../Src/DataManagement/CdmContainerAdaptor.h \
    $$PWD/../Src/DataManagement/IdmHandleDisplayData.h \
    $$PWD/../Src/DataManagement/CdmDeploymentFileConfiguration.h \
    $$PWD/../Src/DataManagement/CdmJsonToObjectMapper.h \
    $$PWD/../Src/DataManagement/CdmUriTemplate.h \
    $$PWD/../Src/DataManagement/CdmEventLogger.h \
    $$PWD/../Src/DataManagement/CdmQueryFactory.h \
    $$PWD/../Src/DataManagement/CdmAntlrErrorListener.h \
    $$PWD/../Src/DataManagement/WmsQL1Lexer.h \
    $$PWD/../Src/DataManagement/WmsQL1Parser.h

SOURCES += ../Src/DataManagement/CdmValueBinaryDocument.cpp \
    ../Src/DataManagement/CdmValueBool.cpp \
    ../Src/DataManagement/CdmValueCharacterDocument.cpp \
    ../Src/DataManagement/CdmClass.cpp \
    ../Src/DataManagement/CdmClassGroup.cpp \
    ../Src/DataManagement/CdmClassManager.cpp \
    ../Src/DataManagement/CdmClassMethod.cpp \
    ../Src/DataManagement/CdmClassValidator.cpp \
    ../Src/DataManagement/CdmValueCounter.cpp \
    ../Src/DataManagement/CdmDataAccessHelper.cpp \
    ../Src/DataManagement/CdmScheme.cpp \
    ../Src/DataManagement/CdmValueDate.cpp \
    ../Src/DataManagement/CdmValueDateTime.cpp \
    ../Src/DataManagement/CdmValueDictIntDouble.cpp \
    ../Src/DataManagement/CdmValueDictIntInt.cpp \
    ../Src/DataManagement/CdmValueDictIntString.cpp \
    ../Src/DataManagement/CdmValueDictStringDouble.cpp \
    ../Src/DataManagement/CdmValueDictStringInt.cpp \
    ../Src/DataManagement/CdmValueDictStringString.cpp \
    ../Src/DataManagement/CdmValueDouble.cpp \
    ../Src/DataManagement/CdmValueListDouble.cpp \
    ../Src/DataManagement/CdmExecutor.cpp \
    ../Src/DataManagement/CdmExecutorPreProcessor.cpp \
    ../Src/DataManagement/CdmExecutorAddOnManager.cpp \
    ../Src/DataManagement/CdmExecutorFunction.cpp \
    ../Src/DataManagement/CdmExecutorValidator.cpp \
    ../Src/DataManagement/CdmExecutorFormula.cpp \
    ../Src/DataManagement/CdmValueFloat.cpp \
    ../Src/DataManagement/CdmValueInt.cpp \
    ../Src/DataManagement/CdmValueListInt.cpp \
    ../Src/DataManagement/CdmJournalItem.cpp \
    ../Src/DataManagement/CdmLocatedElement.cpp \
    ../Src/DataManagement/CdmValueLong.cpp \
    ../Src/DataManagement/CdmSessionManager.cpp \
    ../Src/DataManagement/CdmMember.cpp \
    ../Src/DataManagement/CdmMessageManager.cpp \
    ../Src/DataManagement/CdmModelElement.cpp \
    ../Src/DataManagement/CdmModelElementBase.cpp \
    ../Src/DataManagement/CdmObject.cpp \
    ../Src/DataManagement/CdmObjectAdaptor.cpp \
    ../Src/DataManagement/CdmObjectContainer.cpp \
    ../Src/DataManagement/CdmContainerManager.cpp \
    ../Src/DataManagement/CdmValueContainerRef.cpp \
    ../Src/DataManagement/CdmContainerServices.cpp \
    ../Src/DataManagement/CdmValueObjectRef.cpp \
    ../Src/DataManagement/CdmProxyBase.cpp \
    ../Src/DataManagement/CdmQuery.cpp \
    ../Src/DataManagement/CdmQueryBuilder.cpp \
    ../Src/DataManagement/CdmQueryElement.cpp \
    ../Src/DataManagement/CdmQueryEnhanced.cpp \
    ../Src/DataManagement/CdmQueryResultElement.cpp \
    ../Src/DataManagement/CdmQueryResultObject.cpp \
    ../Src/DataManagement/CdmRights.cpp \
    ../Src/DataManagement/CdmSettings.cpp \
    ../Src/DataManagement/CdmValueString.cpp \
    ../Src/DataManagement/CdmValueListString.cpp \
    ../Src/DataManagement/CdmSystemVariables.cpp \
    ../Src/DataManagement/CdmValueTime.cpp \
    ../Src/DataManagement/CdmValue.cpp \
    ../Src/DataManagement/CdmValueEnum.cpp \
    ../Src/DataManagement/CdmValueFormula.cpp \
    ../Src/DataManagement/CdmValueListObjects.cpp \
    ../Src/DataManagement/CdmValueUser.cpp \
    ../Src/DataManagement/CdmValueUserGroup.cpp \
    ../Src/UserManagement/CumAccessor.cpp \
    ../Src/UserManagement/CumAccessorRight.cpp \
    ../Src/UserManagement/CumUser.cpp \
    ../Src/UserManagement/CumUserGroup.cpp \
    ../Src/UserManagement/CumUserManager.cpp \
    ../Src/DataManagement/CdmClassDiamondValidator.cpp \
    ../Src/DataManagement/CdmDataAccessConfiguration.cpp \
    ../Src/SimpleApi/CsaValue.cpp \
    ../Src/SimpleApi/CsaModelElement.cpp \
    ../Src/SimpleApi/CsaClass.cpp \
    ../Src/SimpleApi/CsaClassManager.cpp \
    ../Src/SimpleApi/CsaContainerManager.cpp \
    ../Src/SimpleApi/CsaScheme.cpp \
    ../Src/SimpleApi/CsaFactory.cpp \
    ../Src/SimpleApi/CsaManager.cpp \
    ../Src/SimpleApi/CsaMember.cpp \
    ../Src/SimpleApi/CsaObject.cpp \
    ../Src/SimpleApi/CsaObjectContainer.cpp \
    ../Src/SimpleApi/CsaUser.cpp \
    ../Src/SimpleApi/CsaUserGroup.cpp \
    ../Src/SimpleApi/CsaLocatedElement.cpp \
    ../Src/SimpleApi/CsaQuery.cpp \
    ../Src/DataManagement/CdmExecutorRuntime.cpp \
    ../Src/DataManagement/CdmExecutorRuntimeManager.cpp \
    ../Src/DataManagement/CdmExecutorBase.cpp \
    ../Src/DataManagement/CdmExecutorRemote.cpp \
    ../Src/DataManagement/CdmSession.cpp \
    $$PWD/../Src/DataManagement/CdmPackage.cpp \
    $$PWD/../Src/DataManagement/CsaResultObject.cpp \
    $$PWD/../Src/DataManagement/CdmExecutorEngineScript.cpp \
    $$PWD/../Src/DataManagement/CdmExecutorEngineJs.cpp \
    $$PWD/../Src/DataManagement/IdmExecutorEngine.cpp \
    $$PWD/../Src/DataManagement/CdmGlobalContext.cpp \
    $$PWD/../Src/SimpleApi/CsaFunction.cpp \
    $$PWD/../Src/SimpleApi/CsaValueReference.cpp \
    $$PWD/../Src/DataManagement/CdmLogging.cpp \
    $$PWD/../Src/DataManagement/CdmLogEntry.cpp \
    $$PWD/../Src/DataManagement/CdmLogfileWriter.cpp \
    $$PWD/../Src/DataManagement/CdmLoggingAdaptor.cpp \
    $$PWD/../Src/DataManagement/CdmDataProvider.cpp \
    $$PWD/../Src/DataManagement/CdmContainerAdaptor.cpp \
    $$PWD/../Src/DataManagement/CdmConfigManager.cpp \
    $$PWD/../Src/DataManagement/CdmDeploymentFileConfiguration.cpp \
    $$PWD/../Src/DataManagement/CdmJsonToObjectMapper.cpp \
    $$PWD/../Src/DataManagement/CdmUriTemplate.cpp \
    $$PWD/../Src/DataManagement/CdmEventLogger.cpp \
    $$PWD/../Src/DataManagement/CdmQueryFactory.cpp \
    $$PWD/../Src/DataManagement/CdmAntlrErrorListener.cpp \
    $$PWD/../Src/DataManagement/WmsQL1Lexer.cpp \
    $$PWD/../Src/DataManagement/WmsQL1Parser.cpp

DISTFILES += \
    wmsmanager.qmodel
