PRECOMPILED_HEADER = precompile.h

HEADERS += \
    $$PWD/../src/misc/CwmsDynamicParamWidget.h \
    $$PWD/../src/misc/CwmsFormUserDefinedExecutor.h \
    $$PWD/../src/misc/CwmsUIEditor.h \
    $$PWD/precompile.h \
    ../src/ObjectEditor/CoeDataTypeWidget.h \
    ../src/ObjectEditor/CoedtwAddValueDlgIf.h \
    ../src/ObjectEditor/CoedtwBinaryDocument.h \
    ../src/ObjectEditor/CoedtwBool.h \
    ../src/ObjectEditor/CoedtwCharacterDocument.h \
    ../src/ObjectEditor/CoedtwDate.h \
    ../src/ObjectEditor/CoedtwDateTime.h \
    ../src/ObjectEditor/CoedtwDouble.h \
    ../src/ObjectEditor/CoedtwEnum.h \
    ../src/ObjectEditor/CoedtwFormula.h \
    ../src/ObjectEditor/CoedtwInteger.h \
    ../src/ObjectEditor/CoedtwList.h \
    ../src/ObjectEditor/CoedtwLong.h \
    ../src/ObjectEditor/CoedtwObjectListRef.h \
    ../src/ObjectEditor/CoedtwObjectRef.h \
    ../src/ObjectEditor/CoedtwString.h \
    ../src/ObjectEditor/CoedtwTime.h \
    ../src/ObjectEditor/CoedtwUser.h \
    ../src/ObjectEditor/CoedtwUserGroup.h \
    ../src/ObjectEditor/CoeInsertTableDlg.h \
    ../src/ObjectEditor/coetextedit.h \
    ../src/ObjectEditor/CoeTextEditIf.h \
    ../src/ObjectEditor/CoeTextEditMainWindow.h \
    ../src/misc/CwmsAboutDlg.h \
    ../src/misc/CwmsApplicationEditor.h \
    ../src/misc/CwmsApplicationModuleEditor.h \
    ../src/misc/CwmsClassMemberSelection.h \
    ../src/misc/CwmsClassSelectionIf.h \
    ../src/misc/CwmsErrorIf.h \
    ../src/misc/CwmsErrorSettingsIf.h \
    ../src/misc/CwmsEscalationEditorDlg.h \
    ../src/misc/CwmsExportSettingsIf.h \
    ../src/misc/CwmsFormGenericObjectEditor.h \
    ../src/misc/CwmsFormObjectObjectListEditor.h \
    ../src/misc/CwmsFormSearchEditor.h \
    ../src/misc/CwmsFormStandardObjectListEditor.h \
    ../src/misc/CwmsFormViewEditor.h \
    ../src/misc/CwmsguiObjectEditorIf.h \
    ../src/misc/CwmsguiObjectEditorSelector.h \
    ../src/misc/CwmsguiValidator.h \
    ../src/misc/CwmsHelp.h \
    ../src/misc/CwmsImportColumnDlg.h \
    ../src/misc/CwmsImportDlg.h \
    ../src/misc/CwmsJournalViewer.h \
    ../src/misc/CwmsListWidgetHelper.h \
    ../src/misc/CwmsMessenger.h \
    ../src/misc/cwmsobjectchoicecombobox.h \
    ../src/ObjectEditor/CwmsObjectEditor.h \
    ../src/misc/CwmsObjectListEditorBase.h \
    ../src/misc/CwmsObjectListEditorIf.h \
    ../src/misc/CwmsObjectListEditorWidgetIf.h \
    ../src/misc/CwmsObjectListPropertiesDlg.h \
    ../src/misc/CwmsObjectListSelectionIf.h \
    ../src/misc/CwmsObjectObjectListEditorWidget.h \
    ../src/misc/CwmsObjectSelectionIf.h \
    ../src/misc/CwmsPrintingTemplateProperties.h \
    ../src/misc/CwmsQueryEditor.h \
    ../src/misc/CwmsQueryResultViewer.h \
    ../src/RightsManager/CwmsRightsManagerIf.h \
    ../src/misc/CwmsRuntime.h \
    ../src/misc/CwmsRuntimeBase.h \
    ../src/misc/CwmsSearchDlg.h \
    ../src/misc/CwmsSearchWidgetIf.h \
    ../src/misc/CwmsSearchWindow.h \
    ../src/misc/CwmsSearchWindowDlg.h \
    ../src/misc/CwmsShowMessageListDlg.h \
    ../src/misc/CwmsShowResultMessageDlg.h \
    ../src/misc/CwmsSmtpSettings.h \
    ../src/misc/CwmsTranslator.h \
    ../src/misc/CwmsTreeWidgetHelper.h \
    ../src/misc/CwmsUserSelectionBox.h \
     ../src/misc/CwmsViewEditor.h \
    ../src/misc/CwmsViewObjectListEditorWidget.h \
    ../src/misc/CwmsWorkflowDefitionEditor.h \
    ../src/misc/CwmsWorkflowMemberValueEditor.h \
    ../src/misc/CwmsWorkflowStepEditorDlg.h \
    ../src/misc/CwmsWorkflowStepExecutionEditorDlg.h \
    ../src/misc/IwmsguiPlugin.h \
    ../src/misc/IwmsObjectEditorDescriptor.h \
    ../src/misc/IwmsObjectListEditorDescriptor.h \
    ../src/misc/jsedit.h \
    ../src/misc/jshighlighter.h \
    ../src/misc/jstokenizer.h \
    ../src/misc/jsenv.h \
    ../src/wmsgui.h \
    ../src/misc/CwmsErrorMessenger.h \
    ../src/misc/CwmsguiApplicationServices.h \
    ../src/misc/CwmsPluginsIf.h \
    ../src/misc/CwmsPluginsDlg.h \
    ../src/misc/CwmsVariantMapEditor.h \
    ../src/misc/CwmsVariantMapEditorWidget.h \
    ../src/misc/CwmsGuiDataAccessConfiguration.h \
    ../src/misc/CwmsGuiLdapAccessConfiguration.h \
    ../src/misc/CwmsGuiApplicationSelectionIf.h \
    ../src/misc/CwmsGuiDatabaseSelection.h \
    ../src/misc/CwmsGuiLoginIf.h \
    $$PWD/../src/misc/IwmsSciprtEditor.h \
    $$PWD/../src/misc/CwmsTreeCompletionModel.h \
    $$PWD/../src/misc/CwmsTreeCompletionItem.h \
    $$PWD/../src/misc/CwmsJsCompleter.h \
    $$PWD/../src/misc/CwmsDataAccessConfigurator.h \
    $$PWD/../src/misc/CwmsFormObjectRefAssignment.h \
    $$PWD/../src/CwmsFormInteractiveComponentEditor.h \
    $$PWD/../src/misc/CwmsEventClassEditor.h \
    $$PWD/../src/CwmsContainerEditorDlg.h \
    $$PWD/../src/misc/CwmsDateEdit.h \
    $$PWD/../src/misc/CwmsLineEdit.h \
    $$PWD/../src/misc/CwmsTreeWidgetItem.h \
    $$PWD/../src/CwmsObjectBinder.h \
    $$PWD/../src/misc/CwmsContainerUpdateLocker.h \
    ../src/misc/CwmsDynamicParameterDlg.h \
    ../src/misc/CwmsQueryEditorDlg.h

SOURCES += \
    $$PWD/../src/misc/CwmsDynamicParamWidget.cpp \
    $$PWD/../src/misc/CwmsFormUserDefinedExecutor.cpp \
    $$PWD/../src/misc/CwmsUIEditor.cpp \
    ../src/misc/jsedit.cpp \
    ../src/misc/jshighlighter.cpp \
    ../src/misc/jstokenizer.cpp \
    ../src/ObjectEditor/CoeDataTypeWidget.cpp \
    ../src/ObjectEditor/CoedtwAddValueDlgIf.cpp \
    ../src/ObjectEditor/CoedtwBinaryDocument.cpp \
    ../src/ObjectEditor/CoedtwBool.cpp \
    ../src/ObjectEditor/CoedtwCharacterDocument.cpp \
    ../src/ObjectEditor/CoedtwDate.cpp \
    ../src/ObjectEditor/CoedtwDateTime.cpp \
    ../src/ObjectEditor/CoedtwDouble.cpp \
    ../src/ObjectEditor/CoedtwEnum.cpp \
    ../src/ObjectEditor/CoedtwFormula.cpp \
    ../src/ObjectEditor/CoedtwInteger.cpp \
    ../src/ObjectEditor/CoedtwList.cpp \
    ../src/ObjectEditor/CoedtwLong.cpp \
    ../src/ObjectEditor/CoedtwObjectListRef.cpp \
    ../src/ObjectEditor/CoedtwObjectRef.cpp \
    ../src/ObjectEditor/CoedtwString.cpp \
    ../src/ObjectEditor/CoedtwTime.cpp \
    ../src/ObjectEditor/CoedtwUser.cpp \
    ../src/ObjectEditor/CoedtwUserGroup.cpp \
    ../src/ObjectEditor/CoeInsertTableDlg.cpp \
    ../src/ObjectEditor/CoeTextedit.cpp \
    ../src/ObjectEditor/CoeTextEditIf.cpp \
    ../src/ObjectEditor/CoeTextEditMainWindow.cpp \
    ../src/misc/CwmsAboutDlg.cpp \
    ../src/misc/CwmsApplicationEditor.cpp \
    ../src/misc/CwmsApplicationModuleEditor.cpp \
    ../src/misc/CwmsClassMemberSelection.cpp \
    ../src/misc/CwmsClassSelectionIf.cpp \
    ../src/misc/CwmsErrorIf.cpp \
    ../src/misc/CwmsErrorSettingsIf.cpp \
    ../src/misc/CwmsEscalationEditorDlg.cpp \
    ../src/misc/CwmsExportSettingsIf.cpp \
    ../src/misc/CwmsFormGenericObjectEditor.cpp \
    ../src/misc/CwmsFormObjectObjectListEditor.cpp \
    ../src/misc/CwmsFormSearchEditor.cpp \
    ../src/misc/CwmsFormStandardObjectListEditor.cpp \
    ../src/misc/CwmsFormViewEditor.cpp \
    ../src/misc/CwmsguiObjectEditorIf.cpp \
    ../src/misc/CwmsguiObjectEditorSelector.cpp \
    ../src/misc/CwmsguiValidator.cpp \
    ../src/misc/CwmsHelp.cpp \
    ../src/misc/CwmsImportColumnDlg.cpp \
    ../src/misc/CwmsImportDlg.cpp \
    ../src/misc/CwmsJournalViewer.cpp \
    ../src/misc/CwmsListWidgetHelper.cpp \
    ../src/misc/CwmsMessenger.cpp \
    ../src/misc/cwmsobjectchoicecombobox.cpp \
    ../src/ObjectEditor/CwmsObjectEditor.cpp \
    ../src/misc/CwmsObjectListEditorBase.cpp \
    ../src/misc/CwmsObjectListEditorIf.cpp \
    ../src/misc/CwmsObjectListEditorWidgetIf.cpp \
    ../src/misc/CwmsObjectListPropertiesDlg.cpp \
    ../src/misc/CwmsObjectListSelectionIf.cpp \
    ../src/misc/CwmsObjectObjectListEditorWidget.cpp \
    ../src/misc/CwmsObjectSelectionIf.cpp \
    ../src/misc/CwmsPrintingTemplateProperties.cpp \
    ../src/misc/CwmsQueryEditor.cpp \
    ../src/misc/CwmsQueryResultViewer.cpp \
    ../src/RightsManager/CwmsRightsManagerIf.cpp \
    ../src/misc/CwmsRuntime.cpp \
    ../src/misc/CwmsRuntimeBase.cpp \
    ../src/misc/CwmsSearchDlg.cpp \
    ../src/misc/CwmsSearchWidgetIf.cpp \
    ../src/misc/CwmsSearchWindow.cpp \
    ../src/misc/CwmsSearchWindowDlg.cpp \
    ../src/misc/CwmsShowMessageListDlg.cpp \
    ../src/misc/CwmsShowResultMessageDlg.cpp \
    ../src/misc/CwmsSmtpSettings.cpp \
    ../src/misc/CwmsTranslator.cpp \
    ../src/misc/CwmsTreeWidgetHelper.cpp \
    ../src/misc/CwmsUserSelectionBox.cpp \
    ../src/misc/CwmsViewEditor.cpp \
    ../src/misc/CwmsViewObjectListEditorWidget.cpp \
    ../src/misc/CwmsWorkflowDefitionEditor.cpp \
    ../src/misc/CwmsWorkflowMemberValueEditor.cpp \
    ../src/misc/CwmsWorkflowStepEditorDlg.cpp \
    ../src/misc/CwmsWorkflowStepExecutionEditorDlg.cpp \
    ../src/misc/CwmsErrorMessenger.cpp \
    ../src/misc/CwmsguiApplicationServices.cpp \
    ../src/misc/CwmsPluginsIf.cpp \
    ../src/misc/CwmsPluginsDlg.cpp \
    ../src/misc/CwmsVariantMapEditor.cpp \
    ../src/misc/CwmsVariantMapEditorWidget.cpp \
    ../src/misc/CwmsGuiDataAccessConfiguration.cpp \
    ../src/misc/CwmsGuiLdapAccessConfiguration.cpp \
    ../src/misc/CwmsGuiApplicationSelectionIf.cpp \
    ../src/misc/CwmsGuiDatabaseSelection.cpp \
    ../src/misc/CwmsGuiLoginIf.cpp \
    $$PWD/../src/misc/CwmsTreeCompletionModel.cpp \
    $$PWD/../src/misc/CwmsTreeCompletionItem.cpp \
    $$PWD/../src/misc/CwmsJsCompleter.cpp \
    $$PWD/../src/misc/CwmsDataAccessConfigurator.cpp \
    $$PWD/../src/misc/CwmsFormObjectRefAssignment.cpp \
    $$PWD/../src/CwmsFormInteractiveComponentEditor.cpp \
    $$PWD/../src/misc/CwmsEventClassEditor.cpp \
    $$PWD/../src/CwmsContainerEditorDlg.cpp \
    $$PWD/../src/misc/CwmsDateEdit.cpp \
    $$PWD/../src/misc/CwmsLineEdit.cpp \
    $$PWD/../src/misc/CwmsTreeWidgetItem.cpp \
    $$PWD/../src/CwmsObjectBinder.cpp \
    $$PWD/../src/misc/CwmsContainerUpdateLocker.cpp \
    ../src/misc/CwmsDynamicParameterDlg.cpp \
    ../src/misc/CwmsQueryEditorDlg.cpp

FORMS += ../src/ObjectEditor/CoedtwAddValueDlgIf.ui \
    $$PWD/../src/misc/CwmsUIEditor.ui \
    ../src/ObjectEditor/CoeInsertTableDlg.ui \
    ../src/ObjectEditor/CoeTextEditDlg.ui \
    ../src/ObjectEditor/CoeTextEditMainWindow.ui \
    ../src/misc/CwmsAboutDlg.ui \
    ../src/misc/CwmsApplicationEditor.ui \
    ../src/misc/CwmsApplicationModuleEditor.ui \
    ../src/misc/CwmsApplicationSelectionDlg.ui \
    ../src/misc/CwmsClassMemberSelection.ui \
    ../src/misc/cwmsclassselectiondlg.ui \
    ../src/misc/CwmsDatabaseSelection.ui \
    ../src/misc/CwmsErrorDlg.ui \
    ../src/misc/CwmsErrorSettings.ui \
    ../src/misc/CwmsEscalationEditorDlg.ui \
    ../src/misc/CwmsExportDlg.ui \
    ../src/misc/CwmsFormGenericObjectEditor.ui \
    ../src/misc/CwmsFormSearchEditor.ui \
    ../src/misc/CwmsFormStandardObjectListEditor.ui \
    ../src/misc/CwmsFormViewEditor.ui \
    ../src/misc/cwmsguiobjecteditor.ui \
    ../src/misc/CwmsHelp.ui \
    ../src/misc/CwmsImportColumnDlg.ui \
    ../src/misc/CwmsImportDlg.ui \
    ../src/misc/CwmsJournalViewer.ui \
    ../src/misc/cwmslogindlg.ui \
    ../src/ObjectEditor/CwmsObjectEditor.ui \
    ../src/misc/CwmsObjectListEditor.ui \
    ../src/misc/CwmsObjectListEditorWidget.ui \
    ../src/misc/CwmsObjectListPropertiesDlg.ui \
    ../src/misc/CwmsObjectListSelection.ui \
    ../src/misc/CwmsObjectListViewConfiguratorDlg.ui \
    ../src/misc/CwmsObjectObjectListEditorWidget.ui \
    ../src/misc/CwmsObjectSelection.ui \
    ../src/misc/CwmsPrintingTemplateProperties.ui \
    ../src/misc/CwmsQueryEditor.ui \
    ../src/misc/CwmsQueryResultViewer.ui \
    ../src/RightsManager/CwmsRightsManager.ui \
    ../src/misc/CwmsRuntime.ui \
    ../src/misc/CwmsSearchDlg.ui \
    ../src/misc/CwmsSearchWidgetIf.ui \
    ../src/misc/CwmsSearchWindow.ui \
    ../src/misc/CwmsSearchWindowDlg.ui \
    ../src/misc/CwmsShowMessageListDlg.ui \
    ../src/misc/CwmsShowResultMessageDlg.ui \
    ../src/misc/CwmsSmtpSettings.ui \
    ../src/misc/CwmsViewEditor.ui \
    ../src/misc/CwmsViewObjectListEditorWidget.ui \
    ../src/misc/CwmsWorkflowDefinitionEditor.ui \
    ../src/misc/CwmsWorkflowMemberValueEditor.ui \
    ../src/misc/CwmsWorkflowStepEditorDlg.ui \
    ../src/misc/CwmsWorkflowStepExecutionEditorDlg.ui \
    ../src/misc/CwmsPluginManagerIf.ui \
    ../src/misc/CwmsPluginsDlg.ui \
    ../src/misc/CwmsGuiDataAccessConfiguration.ui \
    ../src/misc/CwmsGuiLdapAccessConfiguration.ui \
    $$PWD/../src/misc/CwmsDataAccessConfigurator.ui \
    $$PWD/../src/misc/CwmsFormObjectRefAssignment.ui \
    $$PWD/../src/CwmsFormInteractiveComponentEditor.ui \
    $$PWD/../src/CwmsContainerEditorDlg.ui \
    $$PWD/../src/misc/CwmsEventClassEditor.ui \
    ../src/misc/CwmsDynamicParameterDlg.ui \
    ../src/misc/CwmsQueryEditorDlg.ui

HEADERS += \
    ../src/misc/CwmsScriptableUi.h

SOURCES += \
    ../src/misc/CwmsScriptableUi.cpp


TRANSLATIONS += ./wmsgui_de.ts \
                ./wmsgui_en.ts

RESOURCES += ../src/misc/wmsgui.qrc
