/******************************************************************************
 ** WOGRA Middleware Server Communication Module
 **
 ** @Author Wolfgang GraÃŸhof
 **
 ** This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 ** WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 **(C) copyright by WOGRA technologies All rights reserved
 ******************************************************************************/


// System and QT Includes
#include <QCoreApplication>
#include <qstring.h>
#include <QTextDocument>
#include <qdatetime.h>
#include <QStringList>
#include <qdom.h>
#include <qvariant.h>

// WMS Commons Includes
#include "CwmsJson.h"

// own Includes
#include "wmsdefines.h"
#include "CdmDataProvider.h"
#include "CdmScheme.h"
#include "CdmSystemVariables.h"
#include "CdmSessionManager.h"
#include "CumUserManager.h"
#include "CdmClass.h"
#include "CumUser.h"
#include "CdmLogging.h"
#include "CdmClassGroup.h"
#include "CdmRights.h"
#include "CdmValueListInt.h"
#include "CdmValueListDouble.h"
#include "CdmValueListString.h"
#include "CdmValueDictIntString.h"
#include "CdmValueDictIntInt.h"
#include "CdmValueDictIntDouble.h"
#include "CdmValueDictStringString.h"
#include "CdmValueDictStringInt.h"
#include "CdmValueDictStringDouble.h"
#include "CdmMember.h"


/** +-=---------------------------------------------------------Sa 20. Aug 00:02:48 2005----------*
 * @method  CdmMember::CdmMember                             // private                           *
 * @return                                                   //                                   *
 * @param   long p_lDbId                                     // Database Id                       *
 * @param   long p_lId                                       //                                   *
 * @param   QString p_qstrKeyname                            //                                   *
 * @param   EdmValue p_eDmValue                              //                                   *
 * @param   bool p_bMust                                     //                                   *
 * @param   long p_lSize                                     //                                   *
 * @comment This object can only be generated by CdmClass.                                        *
 *----------------last changed: --------------------------------Sa 20. Aug 00:02:48 2005----------*/
CdmMember::CdmMember(  long p_lDbId,
                       long p_lId,
                       QString p_qstrKeyname,
                       EdmValueType p_eDmValue,
                       bool p_bMust,
                       long p_lSize )
    : CdmModelElement(p_lDbId, p_lId, p_qstrKeyname),
      m_eDmValue(p_eDmValue),
      m_lSize(p_lSize),
      m_lReference(0),
      m_lCounterStart(0),
      m_lClassId(0),
      m_bMust(p_bMust),
      m_bOwner(false),
      m_bUnique(false),
      m_eDmMemberAccess(eDmMemberAccessPublic),
      m_bSystem(true),
      m_iVersion(0),
      m_cCdmRights(this),
      m_rpCdmGroup(nullptr),
      m_bPersistent(true),
      m_bIsTree(true)
{
}


/** +-=---------------------------------------------------------Sa 20. Aug 00:02:56 2005----------*
 * @method  CdmMember::CdmMember                             // public                            *
 * @return                                                   //                                   *
 * @param   QDomElement& p_rqDomElement                      //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 20. Aug 00:02:56 2005----------*/
CdmMember::CdmMember(  QDomElement& p_rqDomElement )
    : CdmModelElement(p_rqDomElement),
      m_eDmValue(eDmValueNone),
      m_lSize(0),
      m_lReference(0),
      m_lCounterStart(0),
      m_lClassId(0),
      m_bMust(false),
      m_bOwner(false),
      m_bUnique(false),
      m_eDmMemberAccess(eDmMemberAccessPublic),
      m_bSystem(true),
      m_iVersion(0),
      m_cCdmRights(this),
      m_rpCdmGroup(nullptr),
      m_bPersistent(true),
      m_bIsTree(true)
{
    XmlImportMember(p_rqDomElement);
}

/** +-=---------------------------------------------------------Fr 7. Dez 10:47:55 2012-----------*
 * @method  CdmMember::CdmMember                             // public                            *
 * @return                                                   //                                   *
 * @param   QVariantMap& p_qMember                          //                                   *
 * @param   long p_lClassId                                  //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Fr 7. Dez 10:47:55 2012-----------*/
CdmMember::CdmMember(QVariantMap& p_qMember, long p_lClassId)
    : CdmModelElement(p_qMember),
      m_eDmValue(eDmValueNone),
      m_lSize(0),
      m_lReference(0),
      m_lCounterStart(0),
      m_lClassId(p_lClassId),
      m_bMust(false),
      m_bOwner(false),
      m_bUnique(false),
      m_eDmMemberAccess(eDmMemberAccessPublic),
      m_bSystem(true),
      m_iVersion(0),
      m_cCdmRights(this),
      m_rpCdmGroup(nullptr),
      m_bPersistent(true),
      m_bIsTree(true)
{
    SetVariant(p_qMember);
}

/** +-=---------------------------------------------------------Sa 20. Aug 12:47:07 2005----------*
 * @method  CdmMember::~CdmMember                            // private, virtual                  *
 * @return  void                                             //                                   *
 * @comment The Destructor of Class CdmMember. This object could only be destroyed from CdmClass. *
 *----------------last changed: --------------------------------Sa 20. Aug 12:47:07 2005----------*/
CdmMember::~CdmMember(  )
{
}

/** +-=---------------------------------------------------------Mo 30. Apr 13:17:10 2012----------*
 * @method  CdmMember::SetVariant                            // public                            *
 * @return  void                                             //                                   *
 * @param   QVariantMap& p_rqvMember                        //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Mo 30. Apr 13:17:10 2012----------*/
void CdmMember::SetVariant(QVariantMap& p_rqvMember)
{
    CdmModelElement::SetVariant(p_rqvMember);
    m_eDmValue = static_cast<EdmValueType>(p_rqvMember[WMS_VALUETYPE].toInt());
    m_eDmMemberAccess = static_cast<EdmMemberAccess>(p_rqvMember[WMS_ACCESS].toInt());
    m_bSystem = p_rqvMember[WMS_SYSTEMVALUE].toBool();
    m_bOwner = p_rqvMember[WMS_OWNER].toBool();
    m_qvDefaultValue = p_rqvMember[WMS_DEFAULT].toString();
    m_lCounterStart = p_rqvMember[WMS_COUNTERSTART].toInt();
    m_lReference  = p_rqvMember[WMS_REFERENCE].toInt();
    m_lClassId = p_rqvMember[WMS_CLASSID].toInt();
    m_qstrComment = p_rqvMember[WMS_COMMENT].toString();
    m_qstrValidationCode = p_rqvMember[WMS_VALIDATION].toString();
    m_bPersistent = p_rqvMember[WMS_PERSISTENT].toBool();
    m_bMust = p_rqvMember[WMS_MUST].toBool();
    m_bIsTree = p_rqvMember[WMS_TREE].toBool();
    m_lSize = p_rqvMember[WMS_SIZE].toInt();
    SetPrefix(p_rqvMember[WMS_PREFIX].toString());
    SetSuffix(p_rqvMember[WMS_SUFFIX].toString());
    SetDecimalCountInput(p_rqvMember[WMS_DECIMALCOUNTINPUT].toInt());
    SetDecimalCountOutput(p_rqvMember[WMS_DECIMALCOUNTOUTPUT].toInt());

    QVariantMap qmRights = p_rqvMember[WMS_RIGHTS].toMap();
    m_cCdmRights.SetVariant(qmRights);

    QVariantMap qvAnnotations = p_rqvMember[WMS_ANNOTATION].toMap();
    QVariantMap qvTranslations = qvAnnotations[WMS_TRANSLATIONS].toMap();

    QVariantMap::iterator qvIt = qvTranslations.begin();
    QVariantMap::iterator qvItEnd = qvTranslations.end();

    for (; qvIt != qvItEnd; ++qvIt)
    {
        QString iId = qvIt.key();
        QVariantMap qvHash = qvIt.value().toMap();

        QString qstrTranslation = qvHash[WMS_TRANSLATION].toString();
        QString qstrComment = qvHash[WMS_COMMENT].toString();
        StringPair pair(qstrTranslation, qstrComment);
        m_qmTranslations.insert(iId, pair);
    }

    QString qstrCategory = p_rqvMember[WMS_CATEGORY].toString();

    if (!qstrCategory.isEmpty())
    {
        CdmClass* pCdmClass = GetClass();

        if (CHKPTR(pCdmClass))
        {
            m_rpCdmGroup = pCdmClass->FindGroupByName(qstrCategory);
        }
    }

    SetModified();
}

/** +-=---------------------------------------------------------Mo 3. Dez 16:44:31 2012-----------*
 * @method  CdmMember::Deploy                                // public                            *
 * @return  void                                             //                                   *
 * @param   QVariantMap& p_rqvMember                        //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Mo 3. Dez 16:44:31 2012-----------*/
void CdmMember::Deploy(QVariantMap& p_rqvMember)
{
    CdmModelElement::Deploy(p_rqvMember);
    m_eDmValue = static_cast<EdmValueType>(p_rqvMember[WMS_VALUETYPE].toInt());
    m_eDmMemberAccess = static_cast<EdmMemberAccess>(p_rqvMember[WMS_ACCESS].toInt());
    m_bSystem = p_rqvMember[WMS_SYSTEMVALUE].toBool();
    m_bOwner = p_rqvMember[WMS_OWNER].toBool();
    m_qvDefaultValue = p_rqvMember[WMS_DEFAULT].toString();
    m_lCounterStart = p_rqvMember[WMS_COUNTERSTART].toInt();
    m_lReference  = p_rqvMember[WMS_REFERENCE].toInt();
    m_qstrComment = p_rqvMember[WMS_COMMENT].toString();
    m_qstrValidationCode = p_rqvMember[WMS_VALIDATION].toString();
    m_bPersistent = p_rqvMember[WMS_PERSISTENT].toBool();
    m_bIsTree = p_rqvMember[WMS_TREE].toBool();
    m_bMust = p_rqvMember[WMS_MUST].toBool();
    m_lSize = p_rqvMember[WMS_SIZE].toInt();
    SetPrefix(p_rqvMember[WMS_PREFIX].toString());
    SetSuffix(p_rqvMember[WMS_SUFFIX].toString());
    SetDecimalCountInput(p_rqvMember[WMS_DECIMALCOUNTINPUT].toInt());
    SetDecimalCountOutput(p_rqvMember[WMS_DECIMALCOUNTOUTPUT].toInt());
    m_bUnique = p_rqvMember[WMS_UNIQUE].toBool();

    if (m_eDmValue == eDmValueObjectRef ||
            m_eDmValue == eDmValueContainerRef)
    {
        QString qstrUri = p_rqvMember[WMS_REFERENCEURI].toString();
        CdmDataProvider* pManager = CdmSessionManager::GetDataProvider();

        if (!qstrUri.isEmpty() && CHKPTR(pManager))
        {
            CdmModelElement* pElement = dynamic_cast<CdmModelElement*>(pManager->GetUriObject(qstrUri));

            if (pElement)
            {
                m_lReference = pElement->GetId();
            }
            else // class not yet created so i have to create it.
            {
                CdmClassManager* pClassManager = GetClassManager();

                if (CHKPTR(pClassManager))
                {
                    QString qstrKeyname = p_rqvMember[WMS_REFERENCEKEYNAME].toString();

                    if (!qstrKeyname.isEmpty())
                    {
                        CdmPackage* pPackage = pClassManager->FindPackageByClassUri(qstrUri);
                        CdmClass* pClass = pClassManager->CreateClass(qstrKeyname, pPackage);

                        if (CHKPTR(pClass))
                        {
                            m_lReference = pClass->GetId();
                        }
                    }
                }
            }
        }
    }

    QVariantMap qvAnnotations = p_rqvMember[WMS_ANNOTATION].toMap();
    QVariantMap qvTranslations = qvAnnotations[WMS_TRANSLATIONS].toMap();
    QVariantMap::iterator qvIt = qvTranslations.begin();
    QVariantMap::iterator qvItEnd = qvTranslations.end();

    for (; qvIt != qvItEnd; ++qvIt)
    {
        QString iId = qvIt.key();
        QVariantMap qvHash = qvIt.value().toMap();

        QString qstrTranslation = qvHash[WMS_TRANSLATION].toString();
        QString qstrComment = qvHash[WMS_COMMENT].toString();
        StringPair pair(qstrTranslation, qstrComment);
        m_qmTranslations.insert(iId, pair);
    }

    QString qstrCategory = p_rqvMember[WMS_CATEGORY].toString();

    if (!qstrCategory.isEmpty())
    {
        CdmClass* pCdmClass = GetClass();

        if (CHKPTR(pCdmClass))
        {
            m_rpCdmGroup = pCdmClass->FindGroupByName(qstrCategory);
        }
    }

    SetModified();
}

/** +-=---------------------------------------------------------Sa 20. Aug 00:03:03 2005----------*
 * @method  CdmMember::IsMust                                // public, const                     *
 * @return  bool                                             //                                   *
 * @comment returns if this Value with this description must have an value.                       *
 *----------------last changed: --------------------------------Sa 20. Aug 00:03:03 2005----------*/
bool CdmMember::IsMust(  ) const
{
    bool bRet = m_bMust;

    if (m_eDmValue == eDmValueListDouble ||
            m_eDmValue == eDmValueListInt ||
            m_eDmValue == eDmValueListString ||
            m_eDmValue == eDmValueDictIntInt ||
            m_eDmValue == eDmValueDictIntDouble ||
            m_eDmValue == eDmValueDictIntString ||
            m_eDmValue == eDmValueDictStringDouble ||
            m_eDmValue == eDmValueDictStringInt ||
            m_eDmValue == eDmValueDictStringString)
    {
        bRet = false;
    }

    return bRet;
}

/** +-=---------------------------------------------------------Sa 20. Aug 00:03:06 2005----------*
 * @method  CdmMember::SetMustValue                          // public                            *
 * @return  void                                             //                                   *
 * @param   bool p_bMust                                     //                                   *
 * @comment This method sets if this is a must value or not.                                      *
 *----------------last changed: --------------------------------Sa 20. Aug 00:03:06 2005----------*/
void CdmMember::SetMustValue(  bool p_bMust )
{
    m_bMust = p_bMust;
    SetModified();
}

/** +-=---------------------------------------------------------Sa 20. Aug 00:03:08 2005----------*
 * @method  CdmMember::SetSize                               // public                            *
 * @return  void                                             //                                   *
 * @param   long p_lSize                                     //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 20. Aug 00:03:08 2005----------*/
void CdmMember::SetSize(  long p_lSize )
{
    m_lSize = p_lSize;
    SetModified();
}

/** +-=---------------------------------------------------------Di 20. Nov 10:04:35 2012----------*
 * @method  CdmMember::GetSize                               // public, const, slots              *
 * @return  long                                             //                                   *
 * @comment returns the size of this Value. This is only relevant, if this Value is a             *
 *          string.                                                                               *
 *----------------last changed: --------------------------------Di 20. Nov 10:04:35 2012----------*/
long CdmMember::GetSize() const
{
    return m_lSize;
}

/** +-=---------------------------------------------------------Di 20. Nov 10:04:46 2012----------*
 * @method  CdmMember::GetValue                              // public, const, slots              *
 * @return  EdmValue                                         //                                   *
 * @comment returns which kind of Value this is.                                                  *
 *----------------last changed: --------------------------------Di 20. Nov 10:04:46 2012----------*/
EdmValueType CdmMember::GetValueType() const
{
    return m_eDmValue;
}

/** +-=---------------------------------------------------------Sa 7. Jan 12:57:54 2006-----------*
 * @method  CdmMember::SetOwner                              // public                            *
 * @return  void                                             //                                   *
 * @param   bool p_bOwner                                    //                                   *
 * @comment This method sets if this member is owner of the value. this makes only sense by       *
 *          objectlistreferences.                                                                 *
 *----------------last changed: Wolfgang GraÃŸhof----------------Sa 7. Jan 12:57:54 2006-----------*/
void CdmMember::SetOwner(  bool p_bOwner )
{
    m_bOwner = p_bOwner;
    SetModified();
}

/** +-=---------------------------------------------------------Sa 9. Feb 11:34:10 2013-----------*
 * @method  CdmMember::IsOwner                               // public, const, slots              *
 * @return  bool                                             //                                   *
 * @comment returns if this member is the owner of the type. makes only sense by                  *
 *          objectlistreferences                                                                  *
 *----------------last changed: --------------------------------Sa 9. Feb 11:34:10 2013-----------*/
bool CdmMember::IsOwner() const
{
    return m_bOwner;
}

/** +-=---------------------------------------------------------Sa 7. Jan 12:58:27 2006-----------*
 * @method  CdmMember::SetUnique                             // public                            *
 * @return  void                                             //                                   *
 * @param   bool p_bUnique                                   //                                   *
 * @comment This method sets if the value of this member only occurs once.                        *
 *----------------last changed: Wolfgang GraÃŸhof----------------Sa 7. Jan 12:58:27 2006-----------*/
void CdmMember::SetUnique(  bool p_bUnique )
{
    m_bUnique = p_bUnique;
    SetModified();
}

/** +-=---------------------------------------------------------Sa 9. Feb 11:34:21 2013-----------*
 * @method  CdmMember::IsUnique                              // public, const, slots              *
 * @return  bool                                             //                                   *
 * @comment This method returns if this value occurs only once in an objectlsit.                  *
 *----------------last changed: --------------------------------Sa 9. Feb 11:34:21 2013-----------*/
bool CdmMember::IsUnique() const
{
    return m_bUnique;
}

/** +-=---------------------------------------------------------Sa 20. Aug 00:03:17 2005----------*
 * @method  CdmMember::SetValue                              // public                            *
 * @return  void                                             //                                   *
 * @param   EdmValue p_eDmValue                              //                                   *
 * @comment sets the Value in the description.                                                    *
 *----------------last changed: --------------------------------Sa 20. Aug 00:03:17 2005----------*/
void CdmMember::SetValueType(EdmValueType p_eDmValue)
{
    if (p_eDmValue != m_eDmValue)
    {
        SetTemporaryData(WMS_MEMBER_ORIGINAL_VALUE_TYPE, m_eDmValue);
        m_eDmValue = p_eDmValue;
        SetModified();
    }
}


/** +-=---------------------------------------------------------Sa 20. Aug 00:03:20 2005----------*
 * @method  CdmMember::SetDefaultValue                       // public                            *
 * @return  void                                             //                                   *
 * @param   const bool p_bDefault                            //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 20. Aug 00:03:20 2005----------*/
void CdmMember::SetDefaultValue(const bool p_bDefault)
{
    m_qvDefaultValue = p_bDefault;
    SetModified();
}

/** +-=---------------------------------------------------------Sa 20. Aug 00:03:23 2005----------*
 * @method  CdmMember::SetDefaultValue                       // public                            *
 * @return  void                                             //                                   *
 * @param   const QString p_qstDefault                       //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 20. Aug 00:03:23 2005----------*/
void CdmMember::SetDefaultValue(const QString p_qstDefault)
{
    m_qvDefaultValue = p_qstDefault;
    SetModified();
}


/** +-=---------------------------------------------------------Sa 20. Aug 00:03:29 2005----------*
 * @method  CdmMember::SetDefaultValue                       // public                            *
 * @return  void                                             //                                   *
 * @param   const int p_iDefault                             //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 20. Aug 00:03:29 2005----------*/
void CdmMember::SetDefaultValue(const int p_iDefault)
{
    m_qvDefaultValue = p_iDefault;
    SetModified();
}

/** +-=---------------------------------------------------------Sa 20. Aug 00:03:33 2005----------*
 * @method  CdmMember::SetDefaultValue                       // public                            *
 * @return  void                                             //                                   *
 * @param   const long p_lDefault                            //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 20. Aug 00:03:33 2005----------*/
void CdmMember::SetDefaultValue(const long p_lDefault)
{
    m_qvDefaultValue = (int)p_lDefault;
    SetModified();
}

/** +-=---------------------------------------------------------Sa 20. Aug 00:03:36 2005----------*
 * @method  CdmMember::SetDefaultValue                       // public                            *
 * @return  void                                             //                                   *
 * @param   const double p_dDefault                          //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 20. Aug 00:03:36 2005----------*/
void CdmMember::SetDefaultValue(const double p_dDefault)
{
    m_qvDefaultValue = p_dDefault;
    SetModified();
}


/** +-=---------------------------------------------------------Sa 20. Aug 00:03:40 2005----------*
 * @method  CdmMember::SetDefaultValue                       // public                            *
 * @return  void                                             //                                   *
 * @param   const float p_fDefault                           //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 20. Aug 00:03:40 2005----------*/
void CdmMember::SetDefaultValue(const float p_fDefault)
{
    m_qvDefaultValue = p_fDefault;
    SetModified();
}

/** +-=---------------------------------------------------------Sa 20. Aug 00:03:43 2005----------*
 * @method  CdmMember::SetDefaultValue                       // public                            *
 * @return  void                                             //                                   *
 * @param   const QDate p_qdDefault                          //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 20. Aug 00:03:43 2005----------*/
void CdmMember::SetDefaultValue(  const QDate p_qdDefault )
{
    m_qvDefaultValue = p_qdDefault;
    SetModified();
}

/** +-=---------------------------------------------------------Sa 20. Aug 00:03:45 2005----------*
 * @method  CdmMember::SetDateDefaultValue                   // public                            *
 * @return  void                                             //                                   *
 * @param   const long p_lDefault                            //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 20. Aug 00:03:45 2005----------*/
void CdmMember::SetDateDefaultValue(  const long p_lDefault )
{
    m_qvDefaultValue = ChangeLongToDate(p_lDefault);
    SetModified();
}


/** +-=---------------------------------------------------------Sa 20. Aug 00:03:49 2005----------*
 * @method  CdmMember::SetDateTimeDefaultValue               // public                            *
 * @return  void                                             //                                   *
 * @param   const double p_dDefault                          //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 20. Aug 00:03:49 2005----------*/
void CdmMember::SetDateTimeDefaultValue(  const double p_dDefault )
{
    m_qvDefaultValue = p_dDefault;
    SetModified();
}


/** +-=---------------------------------------------------------Sa 20. Aug 00:03:54 2005----------*
 * @method  CdmMember::SetDefaultValue                       // public                            *
 * @return  void                                             //                                   *
 * @param   const QDateTime p_qdtDefault                     //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 20. Aug 00:03:54 2005----------*/
void CdmMember::SetDefaultValue(  const QDateTime p_qdtDefault )
{
    m_qvDefaultValue = p_qdtDefault;
    SetModified();
}

/** +-=---------------------------------------------------------Sa 20. Aug 00:03:57 2005----------*
 * @method  CdmMember::SetDefaultValue                       // public                            *
 * @return  void                                             //                                   *
 * @param   const QTime p_qtDefault                          //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 20. Aug 00:03:57 2005----------*/
void CdmMember::SetDefaultValue(  const QTime p_qtDefault )
{
    m_qvDefaultValue = p_qtDefault;
    SetModified();
}

/** +-=---------------------------------------------------------Sa 20. Aug 00:03:59 2005----------*
 * @method  CdmMember::SetTimeDefaultValue                   // public                            *
 * @return  void                                             //                                   *
 * @param   const double p_dDefault                          //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 20. Aug 00:03:59 2005----------*/
void CdmMember::SetTimeDefaultValue(  const double p_dDefault )
{
    m_qvDefaultValue = ChangeDoubleToTime(p_dDefault);
    SetModified();
}


/** +-=---------------------------------------------------------Sa 20. Aug 00:04:02 2005----------*
 * @method  CdmMember::SetDefaultValue                       // public                            *
 * @return  void                                             //                                   *
 * @param   const QVariant p_qvValue                         //                                   *
 * @comment This method sets the new default value.                                               *
 *----------------last changed: --------------------------------Sa 20. Aug 00:04:02 2005----------*/
void CdmMember::SetDefaultValue(  const QVariant p_qvValue )
{
    m_qvDefaultValue = p_qvValue;
    SetModified();
}


/** +-=---------------------------------------------------------Sa 20. Aug 00:04:05 2005----------*
 * @method  CdmMember::GetDefaultValue                       // public, const                     *
 * @return  void                                             //                                   *
 * @param   bool& p_bDefault                                 //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 20. Aug 00:04:05 2005----------*/
void CdmMember::GetDefaultValue(  bool& p_bDefault ) const
{

    p_bDefault = m_qvDefaultValue.toBool();
}

/** +-=---------------------------------------------------------Sa 20. Aug 00:04:08 2005----------*
 * @method  CdmMember::GetDefaultValue                       // public, const                     *
 * @return  void                                             //                                   *
 * @param   QString& p_qstDefault                            //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 20. Aug 00:04:08 2005----------*/
void CdmMember::GetDefaultValue(  QString& p_qstDefault ) const
{
    QString qstrValue = m_qvDefaultValue.toString();

    if (CdmSystemVariables::IsSystemValue(qstrValue))
    {
        qstrValue = CdmSystemVariables::GetValueAsString(qstrValue);
    }

    p_qstDefault = qstrValue;
}

/** +-=---------------------------------------------------------Sa 20. Aug 00:04:11 2005----------*
 * @method  CdmMember::GetDefaultValue                       // public, const                     *
 * @return  void                                             //                                   *
 * @param   int& p_iDefault                                  //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 20. Aug 00:04:11 2005----------*/
void CdmMember::GetDefaultValue(  int& p_iDefault ) const
{
    QString qstrValue = m_qvDefaultValue.toString();

    if (CdmSystemVariables::IsSystemValue(qstrValue))
    {
        qstrValue = CdmSystemVariables::GetValueAsString(qstrValue);
    }

    p_iDefault = qstrValue.toInt();
}

/** +-=---------------------------------------------------------Sa 20. Aug 00:04:14 2005----------*
 * @method  CdmMember::GetDefaultValue                       // public, const                     *
 * @return  void                                             //                                   *
 * @param   long& p_lDefault                                 //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 20. Aug 00:04:14 2005----------*/
void CdmMember::GetDefaultValue(  long& p_lDefault ) const
{
    QString qstrValue = m_qvDefaultValue.toString();

    if (CdmSystemVariables::IsSystemValue(qstrValue))
    {
        qstrValue = CdmSystemVariables::GetValueAsString(qstrValue);
    }

    p_lDefault = qstrValue.toInt();
}

/** +-=---------------------------------------------------------Sa 20. Aug 00:04:17 2005----------*
 * @method  CdmMember::GetDefaultValue                       // public, const                     *
 * @return  void                                             //                                   *
 * @param   double& p_dDefault                               //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 20. Aug 00:04:17 2005----------*/
void CdmMember::GetDefaultValue(  double& p_dDefault ) const
{
    p_dDefault = m_qvDefaultValue.toDouble();
}


/** +-=---------------------------------------------------------Sa 20. Aug 00:04:20 2005----------*
 * @method  CdmMember::GetDefaultValue                       // public, const                     *
 * @return  void                                             //                                   *
 * @param   float& p_fDefault                                //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 20. Aug 00:04:20 2005----------*/
void CdmMember::GetDefaultValue(  float& p_fDefault ) const
{
    p_fDefault = m_qvDefaultValue.toDouble();
}

/** +-=---------------------------------------------------------Sa 20. Aug 00:04:24 2005----------*
 * @method  CdmMember::GetDefaultValue                       // public, const                     *
 * @return  void                                             //                                   *
 * @param   QDate& p_qdDefault                               //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 20. Aug 00:04:24 2005----------*/
void CdmMember::GetDefaultValue(  QDate& p_qdDefault ) const
{
    QString qstrValue = m_qvDefaultValue.toString();

    if (CdmSystemVariables::IsSystemValue(qstrValue))
    {
        qstrValue = CdmSystemVariables::GetValueAsString(qstrValue);
    }

    p_qdDefault = QDate::fromString(qstrValue, Qt::ISODate);
}

/** +-=---------------------------------------------------------Sa 20. Aug 00:04:28 2005----------*
 * @method  CdmMember::GetDateDefaultValue                   // public, const                     *
 * @return  void                                             //                                   *
 * @param   long& p_lDefault                                 //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 20. Aug 00:04:28 2005----------*/
void CdmMember::GetDateDefaultValue(  long& p_lDefault ) const
{
    p_lDefault = ChangeDateToLong(m_qvDefaultValue.toDate());
}


/** +-=---------------------------------------------------------Sa 20. Aug 00:04:31 2005----------*
 * @method  CdmMember::GetDefaultValue                       // public, const                     *
 * @return  void                                             //                                   *
 * @param   QDateTime& p_qdtDefault                          //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 20. Aug 00:04:31 2005----------*/
void CdmMember::GetDefaultValue(  QDateTime& p_qdtDefault ) const
{
    QString qstrValue = m_qvDefaultValue.toString();

    if (CdmSystemVariables::IsSystemValue(qstrValue))
    {
        qstrValue = CdmSystemVariables::GetValueAsString(qstrValue);
    }

    p_qdtDefault = QDateTime::fromString(qstrValue, Qt::ISODate);
    qstrValue = p_qdtDefault.toString();
}

/** +-=---------------------------------------------------------Sa 9. Feb 11:35:17 2013-----------*
 * @method  CdmMember::GetDateTimeDefaultValue               // public, const                     *
 * @return  void                                             //                                   *
 * @param   double& p_dDefault                               //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 9. Feb 11:35:17 2013-----------*/
void CdmMember::GetDateTimeDefaultValue(double& p_dDefault) const
{
    p_dDefault = ChangeDateTimeToDouble(m_qvDefaultValue.toDateTime());
}


/** +-=---------------------------------------------------------Sa 20. Aug 00:04:38 2005----------*
 * @method  CdmMember::GetDefaultValue                       // public, const                     *
 * @return  void                                             //                                   *
 * @param   QTime& p_qtDefault                               //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 20. Aug 00:04:38 2005----------*/
void CdmMember::GetDefaultValue(  QTime& p_qtDefault ) const
{
    QString qstrValue = m_qvDefaultValue.toString();

    if (CdmSystemVariables::IsSystemValue(qstrValue))
    {
        qstrValue = CdmSystemVariables::GetValueAsString(qstrValue);
    }

    p_qtDefault = QTime::fromString(qstrValue, Qt::ISODate);
}

/** +-=---------------------------------------------------------Sa 20. Aug 00:04:41 2005----------*
 * @method  CdmMember::GetTimeDefaultValue                   // public, const                     *
 * @return  void                                             //                                   *
 * @param   double& p_dDefault                               //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 20. Aug 00:04:41 2005----------*/
void CdmMember::GetTimeDefaultValue(  double& p_dDefault ) const
{
    p_dDefault = ChangeTimeToDouble(m_qvDefaultValue.toTime());
}


/** +-=---------------------------------------------------------Mo 19. Nov 10:51:37 2012----------*
 * @method  CdmMember::GetDefaultValue                       // public, const                     *
 * @return  QVariant                                         //                                   *
 * @comment returns the variant of this Value description.                                        *
 *----------------last changed: --------------------------------Mo 19. Nov 10:51:37 2012----------*/
QVariant CdmMember::GetDefaultValue() const
{
    return m_qvDefaultValue;
}

/** +-=---------------------------------------------------------Sa 20. Aug 00:04:46 2005----------*
 * @method  CdmMember::SetClassId                            // public                            *
 * @return  void                                             //                                   *
 * @param   long p_lClassId                                  //                                   *
 * @comment This method sets the class Id for Object Lists and ObjectListRefs.                    *
 *----------------last changed: --------------------------------Sa 20. Aug 00:04:46 2005----------*/
void CdmMember::SetClassId(  long p_lClassId )
{
    m_lClassId = p_lClassId;
    SetModified();
}

/** +-=---------------------------------------------------------Di 20. Nov 10:06:05 2012----------*
 * @method  CdmMember::GetClassId                            // public, const, slots              *
 * @return  long                                             //                                   *
 * @comment This method returns the ClassId for ObjectLists and ObjectListRefs.                   *
 *----------------last changed: --------------------------------Di 20. Nov 10:06:05 2012----------*/
long CdmMember::GetClassId() const
{
    return m_lClassId;
}

/** +-=---------------------------------------------------------Mo 11. Feb 16:56:22 2013----------*
 * @method  CdmMember::GetClass                              // public, const, slots              *
 * @return  CdmClass*                                        //                                   *
 * @comment This method returns the ClassId for ObjectLists and ObjectListRefs.                   *
 *----------------last changed: --------------------------------Mo 11. Feb 16:56:22 2013----------*/
CdmClass* CdmMember::GetClass() const
{
    CdmClass* pCdmClass = nullptr;
    CdmClassManager* pClassManager = GetClassManager();

    if (CHKPTR(pClassManager))
    {
        pCdmClass = pClassManager->FindClassById(m_lClassId);
    }

    return pCdmClass;
}

bool CdmMember::IsExportType(EdmValueType p_eType)
{
    if (p_eType == eDmValueListObjects &&
            p_eType == eDmValueContainerRef)
    {
        return false;
    }

    return true;
}

/** +-=---------------------------------------------------------Sa 20. Aug 00:04:56 2005----------*
 * @method  CdmMember::SetComment                            // public                            *
 * @return  void                                             //                                   *
 * @param   QString p_qstrComment                            //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 20. Aug 00:04:56 2005----------*/
void CdmMember::SetComment(  QString p_qstrComment )
{
    m_qstrComment = p_qstrComment;
    SetModified();
}

/** +-=---------------------------------------------------------Di 20. Nov 10:06:15 2012----------*
 * @method  CdmMember::GetComment                            // public, const, slots              *
 * @return  QString                                          //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Di 20. Nov 10:06:15 2012----------*/
QString CdmMember::GetComment() const
{
    QString qstrRet = m_qstrComment;
    CdmScheme* pCdmDatabase = GetScheme();

    if (CHKPTR(pCdmDatabase))
    {
        QString qstrLanguage = pCdmDatabase->GetCurrentLanguageName();

        if (!qstrLanguage.isEmpty())
        {
            qstrRet = GetTranslationComment(qstrLanguage);
        }
    }

    return qstrRet;
}

/** +-=---------------------------------------------------------Sa 20. Aug 00:05:01 2005----------*
 * @method  CdmMember::SetClassReference                     // public                            *
 * @return  void                                             //                                   *
 * @param   long p_lReference                                //                                   *
 * @comment Sets the reference to a objectlist or object.                                         *
 *----------------last changed: --------------------------------Sa 20. Aug 00:05:01 2005----------*/
void CdmMember::SetClassReference(long p_lReference)
{
    m_lReference = p_lReference;
    SetModified();
}

void CdmMember::SetClassReference(CdmClass* p_pClass)
{
    if (CHKPTR(p_pClass))
    {
        SetClassReference(p_pClass->GetId());
    }
}
CdmClass* CdmMember::GetClassReferencePtr() const
{
    if (m_lReference > 0)
    {
        CdmClassManager* pCdmClassManager = GetClassManager();
        if(CHKPTR(pCdmClassManager))
        {
            CdmClass* pCdmClass = pCdmClassManager->FindClassById(m_lReference);

            if(CHKPTR(pCdmClass))
            {
                return pCdmClass;
            }
        }
    }

    return nullptr;
}

/** +-=---------------------------------------------------------Di 20. Nov 10:06:25 2012----------*
 * @method  CdmMember::GetClassReference                     // public, const, slots              *
 * @return  long                                             //                                   *
 * @comment returns the reference to a objectlist or object.                                      *
 *----------------last changed: --------------------------------Di 20. Nov 10:06:25 2012----------*/
long CdmMember::GetClassReference() const
{
    return m_lReference;
}

/** +-=---------------------------------------------------------Sa 20. Aug 00:05:08 2005----------*
 * @method  CdmMember::SetCounterStart                       // public                            *
 * @return  void                                             //                                   *
 * @param   long p_lCounterStart                             //                                   *
 * @comment This method sets the start value of counters.                                         *
 *----------------last changed: --------------------------------Sa 20. Aug 00:05:08 2005----------*/
void CdmMember::SetCounterStart(  long p_lCounterStart )
{
    m_lCounterStart = p_lCounterStart;
    SetModified();
}

/** +-=---------------------------------------------------------Sa 9. Feb 11:35:42 2013-----------*
 * @method  CdmMember::GetCounterStart                       // public, const, slots              *
 * @return  long                                             //                                   *
 * @comment This method returns the start value f counters.                                       *
 *----------------last changed: --------------------------------Sa 9. Feb 11:35:42 2013-----------*/
long CdmMember::GetCounterStart() const
{
    return m_lCounterStart;
}

/** +-=---------------------------------------------------------Mi 11. Jun 16:39:03 2008----------*
 * @method  CdmMember::SetClassReference                     // public                            *
 * @return  void                                             //                                   *
 * @param   QString p_qstrClassName                          //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Mi 11. Jun 16:39:03 2008----------*/
void CdmMember::SetClassReference(QString p_qstrClassName)
{
    CdmClass* pCdmClassReference = nullptr;

    CdmClassManager* pCdmClassManager = GetClassManager();

    if (CHKPTR(pCdmClassManager))
    {
        pCdmClassReference = pCdmClassManager->FindClassByKeyname(p_qstrClassName);

        if(pCdmClassReference)
        {
            SetClassReference(pCdmClassReference->GetId());
        }
        else
        {
            ERR("Class " + p_qstrClassName + " does not exist!");
        }
    }
}


/** +-=---------------------------------------------------------Di 20. Nov 10:06:59 2012----------*
 * @method  CdmMember::GenerateDocument                      // public, slots                     *
 * @return  QString                                          //                                   *
 * @comment This method generates the documentation of this Member.                               *
 *----------------last changed: --------------------------------Di 20. Nov 10:06:59 2012----------*/
QString CdmMember::GenerateDocument()
{
    QString qstrDocument;
    qstrDocument += "<tr>";
    qstrDocument += "<td>" + GetKeyname() + "</td>";
    qstrDocument += "<td>" + GetValueTypeAsString() + "</td>";
    qstrDocument += "<td>" + GetComment() + "</td>";
    qstrDocument += "<td>";
    qstrDocument += m_qvDefaultValue.toString();
    qstrDocument += "</td>";
    qstrDocument += "<td>";

    if (m_lReference > 0)
    {
        CdmClass* pCdmClass = GetClassReferencePtr();

        if(CHKPTR(pCdmClass))
        {
            qstrDocument += pCdmClass->GetKeyname();
        }
    }

    qstrDocument += "</td>";
    qstrDocument += "</tr>";
    return qstrDocument;
}

/** +-=---------------------------------------------------------Sa 9. Feb 11:36:35 2013-----------*
 * @method  CdmMember::GetValueAsString                      // public, const, slots              *
 * @return  QString                                          //                                   *
 * @comment This method generates from the Value a string translation.                            *
 *----------------last changed: --------------------------------Sa 9. Feb 11:36:35 2013-----------*/
QString CdmMember::GetValueTypeAsString() const
{

    return GetValueTypeAsString(m_eDmValue);
}

/** +-=---------------------------------------------------------Do 20. Sep 15:11:35 2012----------*
 * @method  CdmMember::GetValueAsString                      // public, static                    *
 * @return  QString                                          //                                   *
 * @param   EdmValue p_eValue                                //                                   *
 * @comment This method generates from the Value a string translation.                            *
 *----------------last changed: --------------------------------Do 20. Sep 15:11:35 2012----------*/
QString CdmMember::GetValueTypeAsString(EdmValueType p_eValue)
{
    QString qstrValue;

    switch(p_eValue)
    {
    case eDmValueBool:
        qstrValue = tr("bool");
        break;
    case eDmValueInt:
        qstrValue = tr("int");
        break;
    case eDmValueLong:
        qstrValue = tr("long");
        break;
    case eDmValueFloat:
        qstrValue = tr("float");
        break;
    case eDmValueDouble:
        qstrValue = tr("double");
        break;
    case eDmValueString:
        qstrValue = tr("string");
        break;
    case eDmValueDate:
        qstrValue = tr("date");
        break;
    case eDmValueTime:
        qstrValue = tr("time");
        break;
    case eDmValueDateTime:
        qstrValue = tr("timestamp");
        break;
    case eDmValueObjectRef:
        qstrValue = tr("object reference");
        break;
    case eDmValueContainerRef:
        qstrValue = tr("container reference");
        break;
    case eDmValueCounter:
        qstrValue = tr("counter");
        break;
    case eDmValueBinaryDocument:
        qstrValue = tr("binray document");
        break;
    case eDmValueCharacterDocument:
        qstrValue = tr("text document");
        break;
    case eDmValueListDouble:
        qstrValue = tr("list<double>");
        break;
    case eDmValueListObjects:
        qstrValue = tr("list<object reference>");
        break;
    case eDmValueListInt:
        qstrValue = tr("list<long>");
        break;
    case eDmValueListString:
        qstrValue = tr("list<string>");
        break;
    case eDmValueDictIntInt:
        qstrValue = tr("map<long,long>");
        break;
    case eDmValueDictIntDouble:
        qstrValue = tr("map<long,double>");
        break;
    case eDmValueDictIntString:
        qstrValue = tr("map<long,string>");
        break;
    case eDmValueDictStringDouble:
        qstrValue = tr("map<string,double>");
        break;
    case eDmValueDictStringInt:
        qstrValue = tr("map<string,long>");
        break;
    case eDmValueDictStringString:
        qstrValue = tr("map<string,string>");
        break;
    case eDmValueUserGroup:
        qstrValue = tr("user group");
        break;
    case eDmValueUser:
        qstrValue = tr("user");
        break;
    case eDmValueEnum:
        qstrValue = tr("enum");
        break;
    case eDmValueFormula:
        qstrValue = tr("formula");
        break;
    case eDmValueArray:
        qstrValue = tr("array");
        break;
    default:
        qstrValue = tr("invalid");
    };

    return qstrValue;
}


/** +-=---------------------------------------------------------Sa 9. Feb 11:36:52 2013-----------*
 * @method  CdmMember::IsDisplayMember                       // public, const, slots              *
 * @return  bool                                             //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 9. Feb 11:36:52 2013-----------*/
bool CdmMember::IsDisplayMember() const
{
    bool bRet = false;

    if (IsPersistent())
    {
        switch(m_eDmValue)
        {
        case eDmValueBool:
        case eDmValueInt:
        case eDmValueLong:
        case eDmValueFloat:
        case eDmValueDouble:
        case eDmValueString:
        case eDmValueDate:
        case eDmValueTime:
        case eDmValueDateTime:
        case eDmValueCounter:
        case eDmValueUser:
        case eDmValueEnum:
            bRet = true;
            break;
        default:
            bRet = false;
        };
    }

    return bRet;
}

/** +-=---------------------------------------------------------Sa 9. Feb 11:37:00 2013-----------*
 * @method  CdmMember::IsNumber                              // public, const, slots              *
 * @return  bool                                             //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 9. Feb 11:37:00 2013-----------*/
bool CdmMember::IsNumber() const
{
    bool bRet = false;

    switch(m_eDmValue)
    {
    case eDmValueInt:
    case eDmValueLong:
    case eDmValueFloat:
    case eDmValueDouble:
    case eDmValueCounter:
        bRet = true;
        break;
    default:
        bRet = false;
        break;
    };

    return bRet;
}

/** +-=---------------------------------------------------------Sa 9. Feb 11:37:07 2013-----------*
 * @method  CdmMember::IsList                                // public, const, slots              *
 * @return  bool                                             //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 9. Feb 11:37:07 2013-----------*/
bool CdmMember::IsList() const
{
    bool bRet = false;

    switch(m_eDmValue)
    {
    case eDmValueListString:
    case eDmValueListInt:
    case eDmValueListDouble:
    case eDmValueListObjects:
        bRet = true;
        break;
    default:
        bRet = false;
        break;
    };

    return bRet;
}

/** +-=---------------------------------------------------------Sa 9. Feb 11:37:13 2013-----------*
 * @method  CdmMember::IsMap                                 // public, const, slots              *
 * @return  bool                                             //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 9. Feb 11:37:13 2013-----------*/
bool CdmMember::IsMap() const
{
    bool bRet = false;

    switch(m_eDmValue)
    {
    case eDmValueDictIntDouble:
    case eDmValueDictIntInt:
    case eDmValueDictIntString:
    case eDmValueDictStringDouble:
    case eDmValueDictStringInt:
    case eDmValueDictStringString:
        bRet = true;
        break;
    default:
        bRet = false;
        break;
    };

    return bRet;
}

/** +-=---------------------------------------------------------Sa 9. Feb 11:37:29 2013-----------*
 * @method  CdmMember::IsSystemMember                        // public, const, slots              *
 * @return  bool                                             //                                   *
 * @comment This method returns the systemflag.                                                   *
 *----------------last changed: --------------------------------Sa 9. Feb 11:37:29 2013-----------*/
bool CdmMember::IsSystemMember() const
{
    return m_bSystem;
}

/** +-=---------------------------------------------------------Di 20. Nov 10:08:56 2012----------*
 * @method  CdmMember::SetSystemFlag                         // public, slots                     *
 * @return  void                                             //                                   *
 * @param   bool p_bSystem                                   //                                   *
 * @comment This method sets the systemflag.                                                      *
 *----------------last changed: --------------------------------Di 20. Nov 10:08:56 2012----------*/
void CdmMember::SetSystemFlag(bool p_bSystem)
{
    m_bSystem = p_bSystem;
    SetModified();
}

/** +-=---------------------------------------------------------Sa 9. Feb 11:37:37 2013-----------*
 * @method  CdmMember::GetAccessMode                         // public, const, slots              *
 * @return  EdmMemberAccess                                  //                                   *
 * @comment This method returns the memberaccess mode.                                            *
 *----------------last changed: --------------------------------Sa 9. Feb 11:37:37 2013-----------*/
EdmMemberAccess CdmMember::GetAccessMode() const
{
    return m_eDmMemberAccess;
}

QString CdmMember::GetAccessModeAsString() const
{
    switch (m_eDmMemberAccess)
    {
    case eDmMemberAccessPrivate:
        return WMS_ACCESS_PRIVATE;
        break;
    case eDmMemberAccessProtected:
        return WMS_ACCESS_PROTECTED;
        break;
    case eDmMemberAccessPublic:
        return WMS_ACCESS_PUBLIC;
        break;
    default:
        return "Unknown";
    }
}

/** +-=---------------------------------------------------------Fr 8. Aug 20:12:56 2008-----------*
 * @method  CdmMember::SetMemberAccess                       // public                            *
 * @return  void                                             //                                   *
 * @param   EdmMemberAccess p_eDmMemberAccess                //                                   *
 * @comment This method sets the access for this member.                                          *
 *----------------last changed: --------------------------------Fr 8. Aug 20:12:56 2008-----------*/
void CdmMember::SetMemberAccess(EdmMemberAccess p_eDmMemberAccess)
{
    m_eDmMemberAccess = p_eDmMemberAccess;
    SetModified();
}

/** +-=---------------------------------------------------------Sa 9. Feb 11:37:43 2013-----------*
 * @method  CdmMember::GetVersion                            // public, const, slots              *
 * @return  int                                              //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 9. Feb 11:37:43 2013-----------*/
int CdmMember::GetVersion() const
{
    return m_iVersion;
}

/** +-=---------------------------------------------------------Mo 18. Jun 13:14:15 2012----------*
 * @method  CdmMember::SetVersion                            // public                            *
 * @return  void                                             //                                   *
 * @param   int p_iVersion                                   //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Mo 18. Jun 13:14:15 2012----------*/
void CdmMember::SetVersion(int p_iVersion)
{
    if (m_iVersion != p_iVersion)
    {
        m_iVersion = p_iVersion;
        SetModified();
    }
}

/** +-=---------------------------------------------------------Di 19. Jun 15:57:10 2012----------*
 * @method  CdmMember::SetGroup                              // public                            *
 * @return  void                                             //                                   *
 * @param   CdmClassGroup* p_pCdmGroup                       //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Di 19. Jun 15:57:10 2012----------*/
void CdmMember::SetGroup(CdmClassGroup* p_pCdmGroup)
{
    if (m_rpCdmGroup != p_pCdmGroup)
    {
        m_rpCdmGroup = p_pCdmGroup;
        SetModified();
    }
}

/** +-=---------------------------------------------------------Sa 9. Feb 11:38:03 2013-----------*
 * @method  CdmMember::GetGroup                              // public, const, slots              *
 * @return  const CdmClassGroup*                             //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 9. Feb 11:38:03 2013-----------*/
const CdmClassGroup* CdmMember::GetGroup() const
{
    return m_rpCdmGroup;
}

/** +-=---------------------------------------------------------Sa 9. Feb 11:38:24 2013-----------*
 * @method  CdmMember::GetGroupName                          // public, const, slots              *
 * @return  QString                                          //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 9. Feb 11:38:24 2013-----------*/
QString CdmMember::GetGroupName() const
{
    QString qstrRet;

    if (m_rpCdmGroup)
    {
        qstrRet = m_rpCdmGroup->GetName();
    }

    return qstrRet;
}

/** +-=---------------------------------------------------------Di 20. Nov 10:09:59 2012----------*
 * @method  CdmMember::GetMemberAlignment                    // public, const, slots              *
 * @return  QVariant                                         //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Di 20. Nov 10:09:59 2012----------*/
QVariant CdmMember::GetMemberAlignment() const
{

    QVariant qVariant = int(Qt::AlignLeft | Qt::AlignVCenter);

    if (GetValueType() == eDmValueInt ||
            GetValueType() == eDmValueFloat ||
            GetValueType() == eDmValueDouble ||
            GetValueType() == eDmValueCounter)
    {
        qVariant = int(Qt::AlignRight | Qt::AlignVCenter);
    }

    return qVariant;
}

/** +-=---------------------------------------------------------Di 20. Nov 10:10:13 2012----------*
 * @method  CdmMember::ConvertValueToDisplayString           // public, const, slots              *
 * @return  QString                                          //                                   *
 * @param   QVariant p_qvValue                               //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Di 20. Nov 10:10:13 2012----------*/
QString CdmMember::ConvertValueToDisplayString(QVariant p_qvValue) const
{
    QString qstrRet;

    switch (GetValueType())
    {
    case eDmValueBool:

        if (p_qvValue.toInt() == 0)
        {
            qstrRet = qApp->tr("Nein");
        }
        else
        {
            qstrRet = qApp->tr("Ja");
        }

        break;
    case eDmValueInt:
        qstrRet = GetPrefix();

        if (!GetDisplayConfig().isEmpty())
        {
            qstrRet = QString::asprintf(GetDisplayConfig().toLatin1(), p_qvValue.toInt());
        }
        else
        {
            qstrRet += p_qvValue.toString();
        }

        qstrRet += GetSuffix();
        break;
    case eDmValueFloat:
    case eDmValueDouble:
    {
        qstrRet = GetPrefix();
        QLocale qlDefault;

        if (GetDecimalCountOutput() > 0)
        {
            qstrRet += qlDefault.toString(p_qvValue.toDouble(), 'f', GetDecimalCountOutput());
        }
        else
        {
            qstrRet += qlDefault.toString(p_qvValue.toDouble(), 'f', 2);
        }

        qstrRet += GetSuffix();
        break;
    }
    case eDmValueString:
    case eDmValueCharacterDocument:
    {
        QTextDocument qtext;
        qtext.setHtml(p_qvValue.toString());
        qstrRet = qtext.toPlainText();
        break;
    }
    case eDmValueDate:
    {
        QDate qDate = p_qvValue.toDate();

        if (qDate.isValid() && qDate < QDate(2200,12,31))
        {
            qstrRet = p_qvValue.toDate().toString(Qt::LocalDate);
        }
        else
        {
            qstrRet = "-";
        }

        break;
    }
    case eDmValueDateTime:
        qstrRet = p_qvValue.toDateTime().toString(Qt::LocalDate);
        break;
    case eDmValueTime:
        qstrRet = p_qvValue.toTime().toString(Qt::LocalDate);
        break;
    case eDmValueUser:
    {
        CumUser* pCumUser = nullptr;
        int iId = p_qvValue.toInt();

        if (iId > 0)
        {
            CdmDataProvider* pCdmManager = CdmSessionManager::GetDataProvider();

            if (CHKPTR(pCdmManager))
            {
                CumUserManager* pCumUserManager = pCdmManager->GetUserManager();

                if (CHKPTR(pCumUserManager))
                {
                    pCumUser = pCumUserManager->FindUserById(iId);
                    if (pCumUser)
                    {
                        qstrRet = pCumUser->GetLastName() + " " + pCumUser->GetFirstName();
                    }
                    else
                    {
                        qstrRet = "Unknown User";
                    }

                }
            }
        }

    }
        break;
    case eDmValueEnum:
    {
        QString qstrCode = GetValidationCode();
        QStringList qstrlSelection = qstrCode.split(",");

        int iPos = p_qvValue.toInt();

        if (iPos >= 0 && iPos < qstrlSelection.count())
        {
            qstrRet = qstrlSelection[p_qvValue.toInt()];
        }
    }
        break;
    case eDmValueListString:
    {
        QString qstrDocument = p_qvValue.toString();
        QList<QString> qllValues;
        CdmValueListString::DeserializeXmlToStringList(qstrDocument, qllValues);

        for (auto qllIt = qllValues.begin(); qllIt != qllValues.end();++qllIt)
        {
            qstrRet += *qllIt + " ";
        }
    }
        break;
    case eDmValueListDouble:
    {
        QString qstrDocument = p_qvValue.toString();
        QList<double> qllValues;
        CdmValueListDouble::DeserializeXmlToDoubleList(qstrDocument, qllValues);
        QLocale loc;

        for (auto qllIt = qllValues.begin(); qllIt != qllValues.end();++qllIt)
        {
            qstrRet += loc.toString(*qllIt, 'f', GetDecimalCountOutput()) + " ";
        }
    }
        break;
    case eDmValueListInt:
    {
        QString qstrDocument = p_qvValue.toString();
        QList<int> qllValues;
        CdmValueListInt::DeserializeXmlToIntList(qstrDocument, qllValues);
        QLocale loc;

        for (auto qllIt = qllValues.begin(); qllIt != qllValues.end();++qllIt)
        {
            qstrRet += loc.toString(*qllIt) + " ";
        }
    }
        break;
    case eDmValueDictIntInt:
    {
        QString qstrDocument = p_qvValue.toString();
        QMap<int,int> qmValues;
        CdmValueDictIntInt::DeserializeXmlToMap(qstrDocument, qmValues);
        QLocale loc;

        for (auto qmIt = qmValues.begin(); qmIt != qmValues.end();++qmIt)
        {
            qstrRet += "[" + loc.toString(qmIt.key()) + "-" + loc.toString(qmIt.value()) +"] ";
        }
    }
        break;
    case eDmValueDictIntDouble:
    {
        QString qstrDocument = p_qvValue.toString();
        QMap<int,double> qmValues;
        CdmValueDictIntDouble::DeserializeXmlToMap(qstrDocument, qmValues);
        QLocale loc;

        for (auto qmIt = qmValues.begin(); qmIt != qmValues.end();++qmIt)
        {
            qstrRet += "[" + loc.toString(qmIt.key()) + "-" + loc.toString(qmIt.value(), 'f') +"] ";
        }
    }
        break;
    case eDmValueDictIntString:
    {
        QString qstrDocument = p_qvValue.toString();
        QMap<int,QString> qmValues;
        CdmValueDictIntString::DeserializeXmlToMap(qstrDocument, qmValues);
        QLocale loc;

        for (auto qmIt = qmValues.begin(); qmIt != qmValues.end();++qmIt)
        {
            qstrRet += "[" + loc.toString(qmIt.key()) + "-" + qmIt.value() + "] ";
        }
    }
        break;
    case eDmValueDictStringDouble:
    {
        QString qstrDocument = p_qvValue.toString();
        QMap<QString, double> qmValues;
        CdmValueDictStringDouble::DeserializeXmlToMap(qstrDocument, qmValues);
        QLocale loc;

        for (auto qmIt = qmValues.begin(); qmIt != qmValues.end();++qmIt)
        {
            qstrRet += "[" + qmIt.key() + "-" + loc.toString(qmIt.value(), 'f') + "] ";
        }
    }
        break;
    case eDmValueDictStringInt:
    {
        QString qstrDocument = p_qvValue.toString();
        QMap<QString, int> qmValues;
        CdmValueDictStringInt::DeserializeXmlToMap(qstrDocument, qmValues);
        QLocale loc;

        for (auto qmIt = qmValues.begin(); qmIt != qmValues.end();++qmIt)
        {
            qstrRet += "[" + qmIt.key() + "-" + loc.toString(qmIt.value()) + "] ";
        }
    }
        break;
    case eDmValueDictStringString:
    {
        QString qstrDocument = p_qvValue.toString();
        QMap<QString, QString> qmValues;
        CdmValueDictStringString::DeserializeXmlToMap(qstrDocument, qmValues);
        QLocale loc;

        for (auto qmIt = qmValues.begin(); qmIt != qmValues.end();++qmIt)
        {
            qstrRet += "[" + qmIt.key() + "-" + qmIt.value() + "] ";
        }
    }
        break;
    default:
        qstrRet = p_qvValue.toString();
    }

    return qstrRet;
}

/** +-=---------------------------------------------------------Sa 9. Feb 11:38:49 2013-----------*
 * @method  CdmMember::XmlExport                             // public, const                     *
 * @return  void                                             //                                   *
 * @param   QDomElement& p_rqdeClassMembers                  //                                   *
 * @comment exports the database to a xml file.                                                   *
 *----------------last changed: --------------------------------Sa 9. Feb 11:38:49 2013-----------*/
void CdmMember::XmlExport(QDomElement& p_rqdeClassMembers) const
{

    QDomDocument qddDocument = p_rqdeClassMembers.ownerDocument();

    QDomElement qdeRoot = qddDocument.createElement(WMS_MEMBER);
    p_rqdeClassMembers.appendChild(qdeRoot);

    XmlExportBase(qdeRoot);

    qdeRoot.setAttribute(WMS_MUST, ChangeBoolToString(m_bMust));
    qdeRoot.setAttribute(WMS_VALUETYPE, QString::number(m_eDmValue));
    qdeRoot.setAttribute(WMS_CLASSID, QString::number(m_lClassId));
    qdeRoot.setAttribute(WMS_COUNTERSTART, QString::number(m_lCounterStart));
    qdeRoot.setAttribute(WMS_REFERENCE, QString::number(m_lReference));
    qdeRoot.setAttribute(WMS_SIZE, QString::number(m_lSize));
    qdeRoot.setAttribute(WMS_COMMENT, m_qstrComment);
    qdeRoot.setAttribute(WMS_DEFAULT, m_qvDefaultValue.toString());
}

/** +-=---------------------------------------------------------Sa 20. Aug 00:05:26 2005----------*
 * @method  CdmMember::XmlImportMember                       // public                            *
 * @return  void                                             //                                   *
 * @param   QDomElement& p_rqdeClassMembers                  //                                   *
 * @comment imports the xml file to the local member.                                             *
 *----------------last changed: --------------------------------Sa 20. Aug 00:05:26 2005----------*/
void CdmMember::XmlImportMember(  QDomElement& p_rqdeClassMembers )
{
    m_bMust         = ChangeStringToBool(p_rqdeClassMembers.attribute(WMS_MUST,          ""));
    m_eDmValue      = EdmValueType(p_rqdeClassMembers.attribute(WMS_VALUETYPE,               "").toInt());
    m_lClassId      = p_rqdeClassMembers.attribute(WMS_CLASSID,                          "").toInt();
    m_lCounterStart = p_rqdeClassMembers.attribute(WMS_COUNTERSTART,                     "").toInt();
    m_lReference    = p_rqdeClassMembers.attribute(WMS_REFERENCE,                        "").toInt();
    m_lSize         = p_rqdeClassMembers.attribute(WMS_SIZE,                             "").toInt();
    m_qstrComment   = p_rqdeClassMembers.attribute(WMS_COMMENT,                          "");
    m_qvDefaultValue = p_rqdeClassMembers.attribute(WMS_DEFAULT, "");
}

/** +-=---------------------------------------------------------Sa 20. Aug 00:05:30 2005----------*
 * @method  CdmMember::XmlImport                             // public                            *
 * @return  void                                             //                                   *
 * @param   QDomElement& p_rqdeClassMembers                  //                                   *
 * @comment imports the xml file to the local member.                                             *
 *----------------last changed: --------------------------------Sa 20. Aug 00:05:30 2005----------*/
void CdmMember::XmlImport(  QDomElement& p_rqdeClassMembers )
{
    XmlImportBase(p_rqdeClassMembers);
    XmlImportMember(p_rqdeClassMembers);
}

/** +-=---------------------------------------------------------Sa 9. Feb 11:38:58 2013-----------*
 * @method  CdmMember::GetVariant                            // public, const, virtual            *
 * @return  QVariant                                         //                                   *
 * @comment This method returns the value as string for displaying information.                   *
 *----------------last changed: --------------------------------Sa 9. Feb 11:38:58 2013-----------*/
QVariant CdmMember::GetVariant() const
{
    QVariantMap qmVariant = CdmModelElement::GetVariant().toMap();
    qmVariant.insert(WMS_CAPTION, GetCaption());
    qmVariant.insert(WMS_VALUETYPE, m_eDmValue);
    qmVariant.insert(WMS_VALUETYPENAME, GetEmfType());
    qmVariant.insert(WMS_ACCESS, m_eDmMemberAccess);
    qmVariant.insert(WMS_SYSTEMVALUE, m_bSystem);
    qmVariant.insert(WMS_OWNER, m_bOwner);
    qmVariant.insert(WMS_VALIDATION, m_qstrValidationCode);
    qmVariant.insert(WMS_DEFAULT, m_qvDefaultValue.toString());
    qmVariant.insert(WMS_COUNTERSTART, (int)m_lCounterStart);
    qmVariant.insert(WMS_CLASSID, (int)m_lClassId);
    qmVariant.insert(WMS_COMMENT, GetComment());
    qmVariant.insert(WMS_PERSISTENT, m_bPersistent);
    qmVariant.insert(WMS_MUST, m_bMust);
    qmVariant.insert(WMS_TREE, m_bIsTree);
    qmVariant.insert(WMS_PREFIX, GetPrefix());
    qmVariant.insert(WMS_SUFFIX, GetSuffix());
    qmVariant.insert(WMS_DECIMALCOUNTINPUT, GetDecimalCountInput());
    qmVariant.insert(WMS_DECIMALCOUNTOUTPUT, GetDecimalCountOutput());
    qmVariant.insert(WMS_UNIQUE, m_bUnique);
    qmVariant.insert(WMS_RIGHTS, m_cCdmRights.GetVariant());
    QVariant qvVariant((int)m_lReference);
    qmVariant.insert(WMS_REFERENCE, qvVariant);

    if (m_lReference > 0 && (m_eDmValue == eDmValueContainerRef || m_eDmValue == eDmValueObjectRef))
    {
        CdmClass* pClass = GetClassReferencePtr();

        if (pClass)
        {
            qmVariant.insert(WMS_REFERENCEURI, pClass->GetUriInternal());
            qmVariant.insert(WMS_REFERENCEKEYNAME, pClass->GetKeyname());
        }
    }

    if (m_rpCdmGroup)
    {
        qmVariant.insert(WMS_CATEGORY, m_rpCdmGroup->GetName());
    }

    QVariantMap qvAnnotations;

    QMap<QString, StringPair>::const_iterator qmIt = m_qmTranslations.begin();
    QMap<QString, StringPair>::const_iterator qmItEnd = m_qmTranslations.end();
    QVariantMap qmTranslations;

    for (; qmIt != qmItEnd; ++qmIt)
    {
        QString iId = qmIt.key();
        StringPair pair = qmIt.value();
        QVariantMap qvTranslation;
        qvTranslation.insert(WMS_TRANSLATION, pair.first);
        qvTranslation.insert(WMS_COMMENT, pair.second);
        qmTranslations.insert(iId, qvTranslation);
    }

    qvAnnotations.insert(WMS_TRANSLATION, qmTranslations);
    qmVariant.insert(WMS_ANNOTATION, qvAnnotations);
    return qmVariant;
}

/** +-=---------------------------------------------------------Sa 9. Feb 11:39:26 2013-----------*
 * @method  CdmMember::CheckWriteAccess                      // public, const, slots              *
 * @return  bool                                             //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 9. Feb 11:39:26 2013-----------*/
bool CdmMember::CheckWriteAccess() const
{
    return m_cCdmRights.HasCurrentUserWriteAccess();
}

/** +-=---------------------------------------------------------Sa 9. Feb 11:39:35 2013-----------*
 * @method  CdmMember::CheckReadAccess                       // public, const, slots              *
 * @return  bool                                             //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 9. Feb 11:39:35 2013-----------*/
bool CdmMember::CheckReadAccess() const
{
    return m_cCdmRights.HasCurrentUserReadAccess();
}

/** +-=---------------------------------------------------------Di 20. Nov 10:11:04 2012----------*
 * @method  CdmMember::GetRights                             // public, slots                     *
 * @return  CdmRights&                                       //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Di 20. Nov 10:11:04 2012----------*/
CdmRights& CdmMember::GetRights()
{
    return m_cCdmRights;
}

/** +-=---------------------------------------------------------Sa 9. Feb 11:39:47 2013-----------*
 * @method  CdmMember::HasValidation                         // public, const, slots              *
 * @return  bool                                             //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 9. Feb 11:39:47 2013-----------*/
bool CdmMember::HasValidation() const
{
    return !m_qstrValidationCode.isEmpty();
}


/** +-=---------------------------------------------------------Di 20. Nov 10:11:36 2012----------*
 * @method  CdmMember::GetValidationCode                     // public, const, slots              *
 * @return  QString                                          //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Di 20. Nov 10:11:36 2012----------*/
QString CdmMember::GetValidationCode() const
{
    return m_qstrValidationCode;
}

QString CdmMember::GetValidationCodeBase64() const
{
    QByteArray ba;
    ba.append(m_qstrValidationCode);
    return ba.toBase64();
}

/** +-=---------------------------------------------------------Mo 25. Jun 16:26:56 2012----------*
 * @method  CdmMember::SetValidationCode                     // public                            *
 * @return  void                                             //                                   *
 * @param   QString p_qstrCode                               //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Mo 25. Jun 16:26:56 2012----------*/
void CdmMember::SetValidationCode(QString p_qstrCode)
{
    if (m_qstrValidationCode != p_qstrCode)
    {
        m_qstrValidationCode = p_qstrCode;
        SetModified();
    }
}

/** +-=---------------------------------------------------------Sa 9. Feb 11:40:43 2013-----------*
 * @method  CdmMember::GetCaption                            // public, const, virtual, slots     *
 * @return  QString                                          //                                   *
 * @comment This method returns the caption of this object.                                       *
 *----------------last changed: --------------------------------Sa 9. Feb 11:40:43 2013-----------*/
QString CdmMember::GetCaption() const
{

    QString qstrRet;
    CdmScheme* pCdmDatabase = GetScheme();

    if (CHKPTR(pCdmDatabase))
    {
        QString qstrLanguage = pCdmDatabase->GetCurrentLanguageName();

        if (!qstrLanguage.isEmpty())
        {
            qstrRet = GetTranslation(qstrLanguage);
        }
    }

    if (qstrRet.isEmpty())
    {
        qstrRet = CdmModelElement::GetCaption();
    }

    return qstrRet;
}

/** +-=---------------------------------------------------------Mo 20. Aug 12:01:25 2012----------*
 * @method  CdmMember::SetTranslation                        // public                            *
 * @return  void                                             //                                   *
 * @param   QString p_qstrLanguage                           //                                   *
 * @param   QString p_qstrTranslation                        //                                   *
 * @param   QString p_qstrComment                            //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Mo 20. Aug 12:01:25 2012----------*/
void CdmMember::SetTranslation(QString p_qstrLanguage,
                               QString p_qstrTranslation,
                               QString p_qstrComment)
{
    CdmScheme* pScheme = GetScheme();

    if (CHKPTR(pScheme))
    {
        if (pScheme->GetLanguageId(p_qstrLanguage) > 0)
        {
            StringPair qPair(p_qstrTranslation, p_qstrComment);
            m_qmTranslations.insert(p_qstrLanguage, qPair);
            SetModified();
        }
        else
        {
            ERR("Language " + p_qstrLanguage + " for translation not found.");
        }
    }
}

/** +-=---------------------------------------------------------Mi 4. Jul 14:49:32 2012-----------*
 * @method  CdmMember::GetTranslation                        // public, const                     *
 * @return  QString                                          //                                   *
 * @param   int p_iLanguageId                                //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Mi 4. Jul 14:49:32 2012-----------*/
QString CdmMember::GetTranslation(QString p_iLanguageId) const
{
    QString qstrRet;

    if (m_qmTranslations.contains(p_iLanguageId))
    {
        StringPair qPair = m_qmTranslations[p_iLanguageId];
        qstrRet = qPair.first;
    }

    return qstrRet;
}

/** +-=---------------------------------------------------------Mo 20. Aug 12:00:58 2012----------*
 * @method  CdmMember::GetTranslations                       // public                            *
 * @return  QMap<int, StringPair>&                           //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Mo 20. Aug 12:00:58 2012----------*/
QMap<QString, StringPair>& CdmMember::GetTranslations()
{
    return m_qmTranslations;
}

/** +-=---------------------------------------------------------Sa 9. Feb 11:41:11 2013-----------*
 * @method  CdmMember::GetSelectionList                      // public, const, slots              *
 * @return  QStringList                                      //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 9. Feb 11:41:11 2013-----------*/
QStringList CdmMember::GetSelectionList() const
{
    QStringList qstrlSelection;
    QString qstrCode = GetValidationCode();
    qstrCode = qstrCode.replace(", ", ",");
    qstrlSelection = qstrCode.split(",", QString::SkipEmptyParts);
    return qstrlSelection;
}

/** +-=---------------------------------------------------------Mo 20. Aug 10:57:09 2012----------*
 * @method  CdmMember::GetTranslationComment                 // public, const                     *
 * @return  QString                                          //                                   *
 * @param   int p_iLanguageId                                //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Mo 20. Aug 10:57:09 2012----------*/
QString CdmMember::GetTranslationComment(QString p_iLanguageId) const
{
    QString qstrRet;

    if (m_qmTranslations.contains(p_iLanguageId))
    {
        StringPair qPair = m_qmTranslations[p_iLanguageId];
        qstrRet = qPair.second;
    }

    return qstrRet;
}

/** +-=---------------------------------------------------------Mo 20. Aug 13:27:12 2012----------*
 * @method  CdmMember::DeleteTranslation                     // public                            *
 * @return  void                                             //                                   *
 * @param   int p_iId                                        //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Mo 20. Aug 13:27:12 2012----------*/
void CdmMember::DeleteTranslation(QString p_iId)
{
    m_qmTranslations.remove(p_iId);
    SetModified();
}

/** +-=---------------------------------------------------------Sa 9. Feb 11:41:37 2013-----------*
 * @method  CdmMember::IsPersistent                          // public, const                     *
 * @return  bool                                             //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 9. Feb 11:41:37 2013-----------*/
bool CdmMember::IsPersistent() const
{
    return m_bPersistent;
}

/** +-=---------------------------------------------------------Mo 1. Okt 09:33:26 2012-----------*
 * @method  CdmMember::SetPersistent                         // public                            *
 * @return  void                                             //                                   *
 * @param   bool p_bPersistent                               //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Mo 1. Okt 09:33:26 2012-----------*/
void CdmMember::SetPersistent(bool p_bPersistent)
{
    m_bPersistent = p_bPersistent;
    SetModified();
}

/** +-=---------------------------------------------------------Mo 10. Dez 10:13:23 2012----------*
 * @method  CdmMember::SetTree                               // public                            *
 * @return  void                                             //                                   *
 * @param   bool p_bTree                                     //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Mo 10. Dez 10:13:23 2012----------*/
void CdmMember::SetTree(bool p_bTree)
{
    m_bIsTree = p_bTree;
    SetModified();
}

/** +-=---------------------------------------------------------Sa 9. Feb 11:41:46 2013-----------*
 * @method  CdmMember::IsTree                                // public, const                     *
 * @return  bool                                             //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 9. Feb 11:41:46 2013-----------*/
bool CdmMember::IsTree() const
{
    return m_bIsTree;
}

/** +-=---------------------------------------------------------Sa 9. Feb 11:41:57 2013-----------*
 * @method  CdmMember::IsMember                              // public, const, virtual, slots     *
 * @return  bool                                             //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 9. Feb 11:41:57 2013-----------*/
bool CdmMember::IsMember() const
{

    return true;
}

/** +-=---------------------------------------------------------Sa 9. Feb 11:42:03 2013-----------*
 * @method  CdmMember::GetUri                                // public, const, virtual, slots     *
 * @return  QString                                          //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 9. Feb 11:42:03 2013-----------*/
QString CdmMember::GetUri() const
{
    QString qstrUri;
    const CdmClass* pClass = GetClass();

    if (CHKPTR(pClass))
    {
        qstrUri = CreateUri(WMS_URI_MEMBER, pClass->GetFullQualifiedName(), GetKeyname());
    }

    return qstrUri;
}

QString CdmMember::GetUriInternal() const
{
    QString qstrUri;
    const CdmClass* pClass = GetClass();

    if (CHKPTR(pClass))
    {
        qstrUri = CreateUriPath(WMS_URI_MEMBER, pClass->GetFullQualifiedName(), GetKeyname(), "");
    }

    return qstrUri;
}

/** +-=---------------------------------------------------------Sa 9. Feb 11:42:48 2013-----------*
 * @method  CdmMember::GetEmfType                            // public, const                     *
 * @return  QString                                          //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 9. Feb 11:42:48 2013-----------*/
QString CdmMember::GetEmfType() const
{
    QString qstrValue;

    switch(m_eDmValue)
    {
    case eDmValueBool:
        qstrValue = WMS_EMF_TYPE_BOOL;
        break;
    case eDmValueInt:
        qstrValue = WMS_EMF_TYPE_INT;
        break;
    case eDmValueLong:
        qstrValue = WMS_EMF_TYPE_LONG;
        break;
    case eDmValueFloat:
        qstrValue = WMS_EMF_TYPE_FLOAT;
        break;
    case eDmValueDouble:
        qstrValue = WMS_EMF_TYPE_DOUBLE;
        break;
    case eDmValueString:
        qstrValue = WMS_EMF_TYPE_STRING;
        break;
    case eDmValueDate:
        qstrValue = WMS_EMF_TYPE_DATE;
        break;
    case eDmValueTime:
        qstrValue = WMS_EMF_TYPE_TIME;
        break;
    case eDmValueDateTime:
        qstrValue = WMS_EMF_TYPE_DATETIME;
        break;
    case eDmValueObjectRef:
        qstrValue = WMS_EMF_TYPE_OBJECTREF;
        break;
    case eDmValueContainerRef:
    {
        qstrValue = WMS_EMF_TYPE_CONTAINER;
        CdmClass* pClass = GetClassReferencePtr();

        if (pClass)
        {
            qstrValue += "<" + pClass->GetKeyname() +">";
        }
        else
        {
            qstrValue += "<void>";
        }
    }
        break;
    case eDmValueCounter:
        qstrValue = WMS_EMF_TYPE_COUNTER;
        break;
    case eDmValueBinaryDocument:
        qstrValue = WMS_EMF_TYPE_BINARYDOCUMENT;
        break;
    case eDmValueCharacterDocument:
        qstrValue = WMS_EMF_TYPE_CHARACTERDOCUMENT;
        break;
    case eDmValueListDouble:
        qstrValue = WMS_EMF_TYPE_LISTDOUBLES;
        break;
    case eDmValueListInt:
        qstrValue = WMS_EMF_TYPE_LISTINTS;
        break;
    case eDmValueListObjects:
        qstrValue = "EEList<EObject>";
        break;
    case eDmValueListString:
        qstrValue = WMS_EMF_TYPE_LISTSTRINGS;
        break;
    case eDmValueDictIntInt:
        qstrValue = WMS_EMF_TYPE_DICTINTINT;
        break;
    case eDmValueDictIntDouble:
        qstrValue = WMS_EMF_TYPE_DICTINTDOUBLE;
        break;
    case eDmValueDictIntString:
        qstrValue = "EMap<EInt,EString>";
        break;
    case eDmValueDictStringDouble:
        qstrValue = WMS_EMF_TYPE_DICTSTRINGDOUBLE;
        break;
    case eDmValueDictStringInt:
        qstrValue = WMS_EMF_TYPE_DICTSTRINGINT;
        break;
    case eDmValueDictStringString:
        qstrValue = WMS_EMF_TYPE_DICTSTRINGSTRING;
        break;
    case eDmValueUserGroup:
        qstrValue = WMS_EMF_TYPE_USERGROUP;
        break;
    case eDmValueUser:
        qstrValue = WMS_EMF_TYPE_USER;
        break;
    case eDmValueEnum:
        qstrValue = WMS_EMF_TYPE_ENUM;
        break;
    case eDmValueFormula:
        qstrValue = WMS_EMF_TYPE_FORMULA;
        break;
    default:
        qstrValue = "WMS_EMF_TYPE_UNKNOWN";
    };

    return qstrValue;
}

/** +-=---------------------------------------------------------Sa 9. Feb 11:43:02 2013-----------*
 * @method  CdmMember::IsValidationType                      // public, const, slots              *
 * @return  bool                                             //                                   *
 * @comment                                                                                       *
 *----------------last changed: --------------------------------Sa 9. Feb 11:43:02 2013-----------*/
bool CdmMember::IsValidationType() const
{
    bool bRet = false;

    switch (m_eDmValue)
    {
    case eDmValueBool:
    case eDmValueInt:
    case eDmValueLong:
    case eDmValueFloat:
    case eDmValueDouble:
    case eDmValueString:
    case eDmValueCharacterDocument:
    case eDmValueDate:
    case eDmValueDateTime:
    case eDmValueTime:
        bRet = true;
        break;
    default:
        break;
    }

    return bRet;
}

void CdmMember::SetKeyname(QString p_qstrKeyname)
{
    CdmModelElement::SetKeyname(p_qstrKeyname);
    SetModified();
}

void CdmMember::SetPrefix(QString p_qstrPrefix)
{
    SetConfigItem("prefix", p_qstrPrefix);
    SetModified();
}

QString CdmMember::GetPrefix() const
{
    return GetConfigItem("prefix").toString();
}

void CdmMember::SetDisplayConfig(QString p_qstrPrefix)
{
    SetConfigItem("displayConfig", p_qstrPrefix);
    SetModified();
}

QString CdmMember::GetDisplayConfig() const
{
    return GetConfigItem("displayConfig").toString();
}

void CdmMember::SetSuffix(QString p_qstrSuffix)
{
    SetConfigItem("suffix", p_qstrSuffix);
    SetModified();
}

QString CdmMember::GetSuffix() const
{
    return GetConfigItem("suffix").toString();
}

void CdmMember::SetDecimalCountInput(int p_iDecimalCount)
{
    SetConfigItem("decimalCountInput", p_iDecimalCount);
    SetModified();
}

int CdmMember::GetDecimalCountOutput() const
{
    return GetConfigItem("decimalCountInput").toInt();
}

void CdmMember::SetDecimalCountOutput(int p_iDecimalCount)
{
    SetConfigItem("decimalCountOutput", p_iDecimalCount);
    SetModified();
}

int CdmMember::GetDecimalCountInput() const
{
    return GetConfigItem("decimalCountOutput").toInt();
}

void CdmMember::SetRenderedCheck(QString p_qstrRendered)
{
    SetConfigItem("rendered", p_qstrRendered);
    SetModified();
}

void CdmMember::SetEnabledCheck(QString p_qstrRendered)
{
    SetConfigItem("enabled", p_qstrRendered);
    SetModified();
}

QString CdmMember::GetRenderedCheck() const
{
    return GetConfigItem("rendered").toString();
}

QString CdmMember::GetEnabledCheck() const
{
    return GetConfigItem("enabled").toString();
}


