==== Wql function reference

Class for creating data requests and evaluation results. How you can build WQL's is described in the WQL section.

===== Function Reference

[source, java]
----
WqlResultObject execute(String query)
----

executes an wql and returns the result object. if the result object is null, an error occurred in the execution. You will find logger otuput in the doku.php?id=logging[logger].

*Arguments*

* String query: The wql query which should be executed.

===== Return value

*return* The WqlResultObject which can be used like in the sample. If the wql query is invalid null will returned.

===== Example

[source,java]
----
var query = "select firstName, lastName from Addresses";
var result = wql.execute(query); // the wql result object and it's mehtods are described below

if (result != null) {
   var rows = result.getResultCount();
   var firstNames = new Array(rows);
   var lastNames = new Array(rows);

   for (var counter = 0; counter < rows; ++counter) {
      firstNames[counter] = result.getResultAt(0, counter);
      lastNames[counter] = result.getResultAt(1, counter);      
   }
}
----

==== WqlResultObject
Class for reading result data from an excuted qurey.

===== Function Reference
[source, java]
----
bool containsGrouping();
----

returns if the requested query has a group by part.

[source, java]
----
WmsObject getObjectAt(int row);
----   

returns the object which represents the result set at position index

[source, java]
----
int getObjectIdAt(int row);
----

returns the object behind the given result row.

[source, java]
----
String getResultAsStringAt(int row);
----

returns a complete row of the result as string.
 
[source, java]
----   
var getResultAt(String p_qstrKeyname, int row);
----   

returns the result of the given 
   
[source, java]
----   
var getResultAt(int column, int row);
----

returns the result at given column and row.

be careful to other frameworks we use here column row and not row column. We will add function which works like other frameworks.

[source, java]
----   
int getRowPosOfObjectInResultTree(int objectId);
----

returns the rowpos of the given object in the result tree or -1 if it was not found.

[source, java]
----   
bool isObjectInResultTree(int objectId);
----

is the container of the query a tree structure this function returns true.

[source, java]
----   
WmsObject getFirstResultObject();
----

returns the object from the first result.

[source, java]
----   
int execute();
----

executes the query again.

[source, java]
----   
void clear();
----
clears the result.

[source, java]
----   
WmsObjectCcontainer getContainer();
----
returns the container of the query. Returns null if it is a class query.

[source, java]
----   
Array getResultList();
----
returns the list of results.

[source, java]
----
bool containsResultObject(WmsObject object);
----
searches for the given object in the result object and returns if it was found or not.

[source, java]
----   
bool containsResultObject(int objectId);
----

searches for the given object id in the result object and returns if it was found or not.

[source, java]
----   
int getResultCount();
----

returns the number of results in the resultobject.

[source, java]
----   
int getColumnCount();
----

returns the number of columns in the resultobject.

[source, java]
----   
QString getKeynameAt(int column);
----

returns the member keyname of the column.

[source, java]
----   
String getResultAsDisplayStringAt(int column, int row);
----  

returns the result in from system ressources read format.
