==== Wql

Class for creating data requests and evaluation results. How you can build WQL's is described in the WQL section.

===== Function Reference

[source, java]
----
WqlResultObject execute(String query)
----

executes an wql and returns the result object. if the result object is null, an error occurred in the execution. You will find logger otuput in the doku.php?id=logging[logger].

*Arguments*

* String query: The wql query which should be executed.

===== Return value

*return* The WqlResultObject which can be used like in the sample.

===== Example

[source,java]
----
var query = "select firstName, lastName from Addresses";
var result = wql.execute(query); // the wql result object and it's mehtods are described below

if (result != null) {
   var rows = result.getResultCount();
   var firstNames = new Array(rows);
   var lastNames = new Array(rows);

   for (var counter = 0; counter < rows; ++counter) {
      firstNames[counter] = result.getResultAt(0, counter);
      lastNames[counter] = result.getResultAt(1, counter);      
   }
}
----

==== WqlResultObject
Class for readiing result data from an excuted qurey.

===== Function Reference
todo

   bool containsGrouping();
   
   
   CsaObject getObjectAt(int p_iIndex);
   
   
   int64 getObjectIdAt(int p_iIndex);
   
   String getResultAsStringAt(int p_iIndex);
   
   var getResultAt(QModelIndex& p_index);
   var getResultAt(QString p_qstrKeyname, int p_iPos);
   var getResultAt(int p_iColumn, int p_iRow);
   int getRowPosOfObjectInResultTree(qint64 p_lObjectId);
   bool isObjectInResultTree(qint64 p_lObejctId);
   void addGroupByElement(QString p_qstrElement);
   CsaObject *getFirstResultObject();
   int execute();
   void setContainer(CsaObjectContainer* p_pContainer);
   void clear();
   QObject* getContainer();
   void setContainerId(qint64 p_lId);
   const QVariantList getResultList();
   bool containsResultObject(CsaObject* p_pObject);
   bool containsResultObject(qint64 p_lObjectId);
   int getResultCount();
   int getColumnCount();
   QString getKeynameAt(int p_iSection);
   QVector<QString> getResultElements();
   void setQuery(CdmQuery* p_pEnhanced);
   // CsaLocatedElement interface
   QString getResultAsDisplayStringAt(int p_iColumn, int p_iRow);
  
