/* Generated by Together */

#ifndef CUMLOGGEDIN_H
#define CUMLOGGEDIN_H

// System and QT Inlcudes


// own Includes
#include "datamanager.h"

// forwards
class CumUser;
class QString;



class WMSMANAGER_API CumLoggedIn 
{
private:    

    /**
     * @supplierCardinality 1 
     */
    CumUser * lnkCumUser;
    QDate Date;
    QDateTime LastRequest;
    QString Login;
    QString IP;

   /** +-=---------------------------------------------------------Sat Feb 1 14:24:30 2003--------*
    * @method  CumLoggedIn::CumLoggedIn                      // public                            *
    * @return                                                //                                   *
    * @comment                                                                                    *
    *---------------------------------------------------------------Sat Feb 1 14:24:30 2003-------*/
   public:
      CumLoggedIn(  );

   /** +-=---------------------------------------------------------Sat Feb 1 14:24:35 2003--------*
    * @method  CumLoggedIn::~CumLoggedIn                     // public, virtual                   *
    * @return  void                                          //                                   *
    * @comment The Destructor of Class CumLoggedIn                                                *
    *                                                                                             *
    *---------------------------------------------------------------Sat Feb 1 14:24:35 2003-------*/
   public:
      virtual ~CumLoggedIn(  );
};
#endif //CUMLOGGEDIN_H
