=== Compiling WMS

Requirements:

* Qt Library 5.15.2 or higher (no Qt6 support at the moment)
* GCC (Linux, Unix)
* MinGW or VisualStudio 2012 or higher (Windows)
* XCode, Clang (MacOS)

==== Compiling with Qt-Creator

With Qt the IDE Qt-Creator will be shipped. With this IDE you can open the project file wms.pro and run compilation (Please make sure that Projects>Build settings: “Shadow build” isn't selected). In Qt-Creator you have to define your output e.g. android, iOS or the platform you are running your Qt. If you want to compile WMS for Windows without VisualStudio. You can download from the Qt page the page with MinGW support. In this package you will find the compiler and nothing else must be installed. For further information visit the Qt website in qt-project.org.

Compiling with QTCreator works on linux (with installed GCC), Windows (with installed MinGW) and MacOS (with installed XCode and Clang).

==== Compiling with commandline on Linux

1.  Unzip the wms.zip file.
2.  Go to the wms directory.
3.  start command qmake -o Makefile wms.pro
4.  start make

WMS will be compiled.

=== Setup Data Access

After Installation you have to configure your dataaccess. In the Dataaccess configuration you configure which datasource you, where the data were saved and how to communicate with it. DataAccess is based on the WMS plugin technology and you are able to implement your own dataaccess. In the standard implementation of WMS we deliver 3 dataaccesse plugins. The SQLite plugin of local development and usage (It stores the data in a sqlite database stored local on your computer). The Relational Database Access for central development and usage (it stores the data in a central relational database such as MySQL, PostgreSQL or Oracle DB). With this plugin your team is able to develop together on the system. The last possibility is using the webclient. It is a http rest request system based on JSON to load and save data over a central server. The server is intended for the use of the WMS Runtimes and has not every function you need for development (e.g. User Management). So it is not recommended to use the server for the WMS Development Platform.

==== SQLite Plugin

After starting the WMS Development Platform the login dialog appears. When the login dialog is open click on the “client settings” button on the left side at the bottom of the login dialog. It opens a new dialog in which you can select the dataaccess plugin you want to use. Select here the "Sqlite" plugin. right to the selection you will find a configure button. click it and you can configure your dataaccess to the sqlite database. Here you can define the place on your hard disk where the sqlite database should be stored. You need read and write access to the directory. If you are doing this to a new
file the database scheme must be created in the file. WMS will check this and after clicking OK the database scheme will be created in the file. If no error occurred you can click the “OK” Button in the client configuration and you can login with the username “admin” and password “admin”.

==== RDB Plugin

After starting the WMS Development Platform the login dialog appears. When the login dialog is open click on the “client settings” button on the left side at the bottom of the login dialog. It opens a new dialog in which you can define the dataaccess plugin you want to use. Add a new DataAccess configuration with the "New" Button. It opens the configuration dialog. Here you can set the name of your configuration and select you plugin. Select here the "Relational Database Access" plugin. Below the selection you can configure your dataaccess to the relational database. Make sure that in the WMS root directory (where the WMS App are) the driver of the database is copied (for mysql or maria db it is libmysql). In the WMS directory you will find the sql script for MySQL or Maria DB to create the database structure. open your db editor and execute it. If you need a sqls cript for other databases please contact us, we can provide you with MSSQL, PostgreSQL and Oracle scripts. After executing the script on DB you can login to WMS with user and password "admin".

=== Known Issues while installing or running WMS the first time

==== Linux

Know Issues for Linux.

===== Data Access does not work

if you took a binary version of Qt you have to make sure that the database plugins links to the correct installed library for database connection (E.g. libmysql.so.*). If not you have to recompile the Qt plugins, or installing the required version. You will find out which library is missing if you run ldd on your os.

==== Windows

Know Issues for Windows.

===== Data Access does not work

if your relational database data access does not work (e.g. MySQL or PostgreSQL,…) the reason could be that the installed driver was not found. Check which driver is required (with depends tool) and check if it is installed on your machine and if it is the right version (e.g. 32 Bit 64 Bit).

