== WMS Development Platform
  
The WMS Development Platform (WMSDP) is an executable shipped with WMS. The executable offers all possibilities to create
application with WMS. It can only be started by user with Administrator privileges. How to work with it is explained in this document.
    
=== Proceeding for developing WMS Applications

With WMS you will a 3 step proceeding is advised for successful implementation of applications.

==== 1. Step Modeling the Application

Modeling means that you define the object oriented class- and data structure of your application. First of all you define your classes in a scheme with members, base classes and groups. Have you finished this task the next step is to define which containers are needed to start your application. If you finished your modeling, you already can use this structure for demonstration purposes. Keep in mind every minute you invest in your class structure and data model, saves you a lot of
time in development, testing and bug fixing. In WMS you have the possibility to document your structures. To each class, member and container you are able to add documentation. Use this to make your approaches understandable for the future and to generate system documentation.

==== 2. Step Implementing the validations and business logic

you can begin to implement your business logic and validation code. Validation will be strict divided from business logic and will be implemented direct on members or in classes. So you strictly divide concerns in your application and this makes your code better understandable and readable. In business logic classes you never should implement further validation code. Implement your code after the KISS principle (Keep It Simple and Smart).

==== 3. Step define and design the user interfaces and application

WMS offers with QML a great possibility to implement beautiful responsive user interfaces for desktop, tablet and mobile
devices. Additionally there are multiple generic dialogs integrated, which can be used for simple purposes or for demonstrators. If you want to implement a Web interface you have to use Vaadin to implement the user interfaces for the web. If you have finished your definitions and designs. add the application in the WMS Development Platform and you have your running application and can test it.

Of course you don't have to wait until business logic is developed. You can start with defining and designing your user
interfaces if the model is finished.

==== And Then???

Of course you need further iterations to enhance your model, business logic and user interfaces. Just restart with step 1 and do it until your software can be used by the user.

include::classes.adoc[]

include::objectcontainers.adoc[]

include::wql.adoc[]

include::applications.adoc[]

include::export.adoc[]

include::import.adoc[]

include::journal.adoc[]

include::teams.adoc[]

include::user_manager.adoc[]

include::views.adoc[]

include::rights.adoc[]

include::user_interfaces.adoc[]

include::deployment.adoc[]

include::logging.adoc[]

include::uml.adoc[]

include::functions.adoc[]
